MARAICHAGE_DATA = [
    # ─────────────────────────────────────────────────────────────────────────
    # 1. TOMATE
    # ─────────────────────────────────────────────────────────────────────────
    {
        "nom": "Tomate",
        "nom_scientifique": "Solanum lycopersicum",
        "nom_local": "Tomate (Wolof: tomaate)",
        "famille": "Solanaceae",
        "categorie": "maraichage",
        "icone": "🍅",
        "description": (
            "La tomate est la culture maraîchère la plus importante au Sénégal, "
            "principalement produite dans les Niayes et la Vallée du Fleuve Sénégal. "
            "Elle est cultivée en saison fraîche sous irrigation pour les marchés locaux et l'industrie."
        ),
        "parametres_climatiques": {
            "temp_min_c": 10.0,
            "temp_opt_min_c": 18.0,
            "temp_opt_max_c": 27.0,
            "temp_max_c": 35.0,
            "pluvio_min_mm": 400,
            "pluvio_opt_mm": 700,
            "pluvio_max_mm": 1200,
            "ph_min": 5.5,
            "ph_opt_min": 6.0,
            "ph_opt_max": 6.8,
            "ph_max": 7.5,
            "texture_preferee": "Limono-sableuse bien drainée",
            "ensoleillement_h": 8.0,
        },
        "varietes": [
            {
                "nom": "Mongal F1",
                "origine": "Syngenta / adapté Afrique de l'Ouest",
                "cycle_min_jours": 75,
                "cycle_max_jours": 90,
                "precocite": "Précoce",
                "tolerance_secheresse": False,
                "tolerance_salinite": True,
                "zones_adaptees": ["niayes", "vallee_fleuve", "bassin_arachidier"],
                "rendement_potentiel_t_ha": 40.0,
                "notes": "Hybride très populaire dans les Niayes, bonne résistance au flétrissement bactérien.",
            },
            {
                "nom": "Tropimech",
                "origine": "Heinz / USA, adapté Sénégal",
                "cycle_min_jours": 90,
                "cycle_max_jours": 110,
                "precocite": "Mi-saison",
                "tolerance_secheresse": False,
                "tolerance_salinite": False,
                "zones_adaptees": ["vallee_fleuve", "niayes"],
                "rendement_potentiel_t_ha": 35.0,
                "notes": "Variété industrielle utilisée pour la transformation (concentré de tomate).",
            },
            {
                "nom": "Caraïbo F1",
                "origine": "Clause / France",
                "cycle_min_jours": 80,
                "cycle_max_jours": 95,
                "precocite": "Précoce",
                "tolerance_secheresse": False,
                "tolerance_salinite": True,
                "zones_adaptees": ["niayes", "casamance"],
                "rendement_potentiel_t_ha": 45.0,
                "notes": "Bonne qualité commerciale, fruits fermes bien adaptés au transport.",
            },
            {
                "nom": "Roma VF",
                "origine": "International, large diffusion Afrique",
                "cycle_min_jours": 75,
                "cycle_max_jours": 90,
                "precocite": "Précoce",
                "tolerance_secheresse": True,
                "tolerance_salinite": False,
                "zones_adaptees": ["bassin_arachidier", "senegal_oriental", "casamance"],
                "rendement_potentiel_t_ha": 25.0,
                "notes": "Variété améliorée tolérante au flétrissement, adaptée aux petits producteurs.",
            },
        ],
        "stades": [
            {
                "ordre": 1,
                "nom_stade": "Pépinière / Germination",
                "jours_debut": 0,
                "jours_fin": 7,
                "description": "Semis en pépinière sous ombrage léger ; germination en 5 à 7 jours.",
                "actions_cles": [
                    "Préparer le substrat (mélange terreau + sable fin)",
                    "Semer à 1 cm de profondeur",
                    "Arroser en fine pluie matin et soir",
                    "Maintenir une température entre 20 et 25°C",
                ],
                "indicateurs_visuels": "Levée des cotylédons, plantules uniformes.",
            },
            {
                "ordre": 2,
                "nom_stade": "Croissance en pépinière",
                "jours_debut": 7,
                "jours_fin": 30,
                "description": "Développement des premières feuilles vraies ; plants à 4-5 feuilles prêts au repiquage.",
                "actions_cles": [
                    "Démarier à 1 plant par poquet",
                    "Apporter un engrais de démarrage (NPK 12-24-12)",
                    "Traiter préventivement contre la fonte des semis (Mancozèbe)",
                    "Habituer progressivement les plants au plein soleil",
                ],
                "indicateurs_visuels": "Plants de 15-20 cm, tige robuste, 4-5 feuilles vraies.",
            },
            {
                "ordre": 3,
                "nom_stade": "Repiquage et installation",
                "jours_debut": 30,
                "jours_fin": 45,
                "description": "Repiquage en plein champ à l'écartement recommandé ; installation racinaire.",
                "actions_cles": [
                    "Repiquer en fin d'après-midi ou par temps nuageux",
                    "Arroser abondamment après repiquage",
                    "Installer les tuteurs dès le repiquage",
                    "Apporter le fumier de fond (10-15 t/ha)",
                ],
                "indicateurs_visuels": "Reprise végétative visible en 5-7 jours, nouvelles feuilles émergentes.",
            },
            {
                "ordre": 4,
                "nom_stade": "Floraison",
                "jours_debut": 45,
                "jours_fin": 65,
                "description": "Apparition des premières fleurs jaunes ; stade critique pour la nouaison.",
                "actions_cles": [
                    "Apporter la fumure d'entretien azotée",
                    "Butter et tuteurer les plants",
                    "Surveiller les ravageurs (Tuta absoluta, pucerons)",
                    "Maintenir un arrosage régulier sans excès",
                ],
                "indicateurs_visuels": "Fleurs jaunes en grappes, chute de fleurs anormale signe de stress.",
            },
            {
                "ordre": 5,
                "nom_stade": "Fructification",
                "jours_debut": 65,
                "jours_fin": 85,
                "description": "Grossissement des fruits ; forte demande en eau et en éléments minéraux.",
                "actions_cles": [
                    "Maintenir l'irrigation régulière (éviter alternance sec/humide)",
                    "Apporter potassium et calcium pour la qualité des fruits",
                    "Ébourgeonnage et effeuillage de la base",
                    "Surveiller la nécrose apicale (carence en calcium)",
                ],
                "indicateurs_visuels": "Fruits verts en développement, absence de craquelures.",
            },
            {
                "ordre": 6,
                "nom_stade": "Maturation et récolte",
                "jours_debut": 85,
                "jours_fin": 110,
                "description": "Coloration progressive des fruits du vert au rouge ; récoltes étalées sur 3-4 semaines.",
                "actions_cles": [
                    "Réduire progressivement l'irrigation",
                    "Récolter à maturité commerciale (rouge-orangé)",
                    "Conditionner délicatement pour le transport",
                    "Retirer les fruits malades immédiatement",
                ],
                "indicateurs_visuels": "Fruits rouges fermes, calice vert, coloration uniforme.",
            },
        ],
        "besoins_eau": [
            {
                "stade": "Pépinière",
                "besoin_mm_semaine": 20.0,
                "sensibilite": "Élevée (fonte des semis)",
                "frequence_irrigation": "2 fois par jour en petites quantités",
                "notes": "Arroser en fine pluie ; éviter l'engorgement.",
            },
            {
                "stade": "Repiquage - Installation",
                "besoin_mm_semaine": 35.0,
                "sensibilite": "Élevée",
                "frequence_irrigation": "Quotidienne pendant 10 jours",
                "notes": "Arrosage copieux au repiquage puis maintien de l'humidité pour la reprise.",
            },
            {
                "stade": "Croissance végétative",
                "besoin_mm_semaine": 40.0,
                "sensibilite": "Modérée",
                "frequence_irrigation": "Tous les 2 jours",
                "notes": "Sol maintenu frais sans engorgement.",
            },
            {
                "stade": "Floraison",
                "besoin_mm_semaine": 50.0,
                "sensibilite": "Très élevée",
                "frequence_irrigation": "Quotidienne",
                "notes": "Stress hydrique à la floraison entraîne la chute des fleurs.",
            },
            {
                "stade": "Fructification",
                "besoin_mm_semaine": 55.0,
                "sensibilite": "Très élevée",
                "frequence_irrigation": "Quotidienne",
                "notes": "Irrégularité d'arrosage cause nécrose apicale et craquelures.",
            },
            {
                "stade": "Maturation",
                "besoin_mm_semaine": 25.0,
                "sensibilite": "Modérée",
                "frequence_irrigation": "Tous les 3 jours",
                "notes": "Réduire l'eau en fin de cycle pour améliorer la teneur en sucres et la conservation.",
            },
        ],
        "besoins_nutritionnels": [
            {
                "stade": "Fond de plantation",
                "azote_kg_ha": 0.0,
                "phosphore_kg_ha": 80.0,
                "potassium_kg_ha": 60.0,
                "calcium_kg_ha": 30.0,
                "magnesium_kg_ha": 15.0,
                "engrais_recommandes": "Superphosphate triple (TSP), fumier organique 15-20 t/ha",
                "moment_application": "15 jours avant repiquage",
                "notes": "Incorporer le fumier bien décomposé pour éviter les brûlures racinaires.",
            },
            {
                "stade": "Croissance végétative",
                "azote_kg_ha": 60.0,
                "phosphore_kg_ha": 30.0,
                "potassium_kg_ha": 40.0,
                "calcium_kg_ha": 20.0,
                "magnesium_kg_ha": 10.0,
                "engrais_recommandes": "NPK 15-15-15 ou urée + KCl",
                "moment_application": "J+15 après repiquage",
                "notes": "Premier apport fractionné pour soutenir la croissance.",
            },
            {
                "stade": "Floraison - Fructification",
                "azote_kg_ha": 80.0,
                "phosphore_kg_ha": 20.0,
                "potassium_kg_ha": 100.0,
                "calcium_kg_ha": 40.0,
                "magnesium_kg_ha": 20.0,
                "engrais_recommandes": "NPK 10-10-20 + nitrate de calcium",
                "moment_application": "Début floraison et 3 semaines après",
                "notes": "Potassium et calcium essentiels pour la qualité des fruits et la prévention de la nécrose apicale.",
            },
        ],
        "calendriers": [
            {
                "zone_agro": "niayes",
                "saison": "Saison fraîche (contre-saison)",
                "mois_semis_debut": 10,
                "mois_semis_fin": 12,
                "mois_recolte_debut": 1,
                "mois_recolte_fin": 3,
                "remarques": "Zone de production principale ; brouillard côtier protège des fortes chaleurs.",
            },
            {
                "zone_agro": "vallee_fleuve",
                "saison": "Contre-saison froide",
                "mois_semis_debut": 10,
                "mois_semis_fin": 11,
                "mois_recolte_debut": 1,
                "mois_recolte_fin": 4,
                "remarques": "Production industrielle pour les usines de transformation (Sénégal River area).",
            },
            {
                "zone_agro": "casamance",
                "saison": "Saison sèche",
                "mois_semis_debut": 11,
                "mois_semis_fin": 1,
                "mois_recolte_debut": 2,
                "mois_recolte_fin": 5,
                "remarques": "Possible avec irrigation ; températures plus douces en altitude.",
            },
        ],
        "rendements": [
            {
                "zone_agro": None,
                "pratique": "Traditionnel / petits producteurs",
                "rendement_min_t_ha": 8.0,
                "rendement_max_t_ha": 15.0,
                "rendement_moyen_t_ha": 11.0,
                "unite": "t/ha",
                "source": "ISRA / ANCAR Sénégal",
                "annee_reference": 2022,
            },
            {
                "zone_agro": None,
                "pratique": "Amélioré avec intrants et irrigation goutte-à-goutte",
                "rendement_min_t_ha": 25.0,
                "rendement_max_t_ha": 50.0,
                "rendement_moyen_t_ha": 35.0,
                "unite": "t/ha",
                "source": "ISRA / Projets FAO Sénégal",
                "annee_reference": 2023,
            },
        ],
        "maladies": [
            {
                "nom": "Mildiou de la tomate",
                "nom_scientifique": "Phytophthora infestans",
                "pathogene_type": "Oomycète",
                "symptomes": "Taches brunes huileuses sur feuilles, cotonneux blanc sur la face inférieure, pourriture rapide des fruits.",
                "conditions_favorables": "Humidité élevée (>90%), températures fraîches (15-20°C), brouillard côtier dans les Niayes.",
                "frequence": "Fréquente",
                "gravite": "Élevée",
                "stade_sensible": "Floraison - Fructification",
                "pertes_estimees": "30-80% en cas d'attaque sévère",
                "prevention": "Variétés résistantes, espacement suffisant, arrosage au pied, élimination des débris végétaux.",
                "traitement": "Mancozèbe 2,5 kg/ha en préventif, Chlorothalonil 2 L/ha, alternance des fongicides.",
            },
            {
                "nom": "Flétrissement bactérien",
                "nom_scientifique": "Ralstonia solanacearum",
                "pathogene_type": "Bactérie",
                "symptomes": "Flétrissement soudain et irréversible des plants en pleine chaleur, vasculaire bruni à la coupe.",
                "conditions_favorables": "Températures élevées (>25°C), sol humide, blessures racinaires (nématodes, façons culturales).",
                "frequence": "Très fréquente dans les Niayes",
                "gravite": "Très élevée",
                "stade_sensible": "Toute la culture",
                "pertes_estimees": "20-100% selon la pression",
                "prevention": "Rotation longue (3 ans), variétés tolérantes (Mongal F1), désinfection du matériel.",
                "traitement": "Aucun traitement curatif efficace ; arracher et brûler les plants atteints.",
            },
            {
                "nom": "Alternariose",
                "nom_scientifique": "Alternaria solani",
                "pathogene_type": "Champignon",
                "symptomes": "Taches brunes concentriques (cibles) sur feuilles et tiges, défoliation progressive.",
                "conditions_favorables": "Alternance humide/sec, températures 25-30°C, plantes affaiblies.",
                "frequence": "Fréquente",
                "gravite": "Modérée",
                "stade_sensible": "Croissance végétative - Fructification",
                "pertes_estimees": "10-30%",
                "prevention": "Éviter les blessures, équilibre nutritionnel, éliminer les feuilles basses malades.",
                "traitement": "Mancozèbe 2 kg/ha, Chlorothalonil à la dose homologuée.",
            },
            {
                "nom": "Tuta absoluta (mineuse de la tomate)",
                "nom_scientifique": "Tuta absoluta",
                "pathogene_type": "Insecte ravageur (Lépidoptère)",
                "symptomes": "Galeries sinueuses dans les feuilles, mines blanchâtres, dégâts sur fruits (galeries avec excréments noirs).",
                "conditions_favorables": "Températures élevées, culture sous abri ou en plein champ toute l'année.",
                "frequence": "Très fréquente (ravageur invasif)",
                "gravite": "Très élevée",
                "stade_sensible": "Toute la culture",
                "pertes_estimees": "50-100% sans lutte",
                "prevention": "Filets anti-insectes en pépinière, pièges à phéromones, rotation culturale.",
                "traitement": "Décis (deltaméthrine) 0,5 L/ha, Lambdacyhalothrine 0,3 L/ha, Bacillus thuringiensis en bio.",
            },
            {
                "nom": "Nématodes des racines",
                "nom_scientifique": "Meloidogyne incognita / M. javanica",
                "pathogene_type": "Nématode",
                "symptomes": "Galles sur racines, rabougrissement, jaunissement, flétrissement par forte chaleur.",
                "conditions_favorables": "Sols sableux des Niayes, températures élevées, monoculture.",
                "frequence": "Très fréquente dans les Niayes",
                "gravite": "Élevée",
                "stade_sensible": "Toute la culture",
                "pertes_estimees": "20-50%",
                "prevention": "Rotation avec céréales ou légumineuses, solarisation du sol, variétés résistantes.",
                "traitement": "Nématicides au repiquage (Carbofuran avec précautions), plantes pièges (Crotalaria).",
            },
        ],
        "ravageurs": [
            {
                "nom": "Mouche blanche",
                "nom_scientifique": "Bemisia tabaci",
                "type_ravageur": "Insecte piqueur-suceur",
                "description": "Petit insecte blanc de 1,5 mm, très polyphage, vecteur de viroses.",
                "symptomes_degats": "Miellat collant, fumagine noire, jaunissement, transmission de virus (TYLCV).",
                "frequence": "Très fréquente",
                "gravite": "Élevée (surtout en tant que vecteur viral)",
                "stade_sensible": "Toute la culture",
                "pertes_estimees": "10-40% directement, plus par viroses",
                "prevention": "Pièges jaunes engluants, bâches réfléchissantes, filets insect-proof.",
                "lutte": "Confidor (imidaclopride) 0,5 L/ha, savon insecticide, Actellic 50 EC.",
            },
            {
                "nom": "Pucerons",
                "nom_scientifique": "Myzus persicae / Aphis gossypii",
                "type_ravageur": "Insecte piqueur-suceur",
                "description": "Colonies de pucerons verts ou noirs sur jeunes pousses et sous-face des feuilles.",
                "symptomes_degats": "Enroulement des feuilles, miellat, fumagine, transmission de virus.",
                "frequence": "Fréquente",
                "gravite": "Modérée à élevée",
                "stade_sensible": "Végétation - Floraison",
                "pertes_estimees": "5-20%",
                "prevention": "Favoriser les ennemis naturels (coccinelles), pièges jaunes.",
                "lutte": "Confidor 0,3 L/ha, Cypermethrine 0,5 L/ha, savon noir dilué.",
            },
            {
                "nom": "Chenille légionnaire",
                "nom_scientifique": "Spodoptera frugiperda / S. littoralis",
                "type_ravageur": "Insecte défoliateur (Lépidoptère)",
                "description": "Chenilles grises-vertes nocturnes, très voraces, attaquent feuilles et fruits.",
                "symptomes_degats": "Défoliation importante, perforations et galeries dans les fruits.",
                "frequence": "Fréquente en hivernage",
                "gravite": "Élevée",
                "stade_sensible": "Croissance végétative - Fructification",
                "pertes_estimees": "15-35%",
                "prevention": "Ramassage manuel des œufs et jeunes chenilles, désherbage.",
                "lutte": "Décis 2,5 EC (deltaméthrine) 0,5 L/ha, Lambdacyhalothrine 0,3 L/ha.",
            },
            {
                "nom": "Acarien tétranyque",
                "nom_scientifique": "Tetranychus urticae",
                "type_ravageur": "Acarien",
                "description": "Minuscules acariens jaune-vert sur face inférieure des feuilles, toiles fines visibles.",
                "symptomes_degats": "Décoloration bronzée des feuilles, dessèchement en cas d'attaque forte.",
                "frequence": "Fréquente en saison sèche et chaude",
                "gravite": "Modérée",
                "stade_sensible": "Fructification - Maturation",
                "pertes_estimees": "10-20%",
                "prevention": "Maintenir l'humidité, favoriser les prédateurs (Phytoseiidae).",
                "lutte": "Actellic 50 EC 1 L/ha, huile de neem, soufre mouillable.",
            },
        ],
        "recommandations": [
            {
                "zone_agro": None,
                "categorie_reco": "Irrigation",
                "titre": "Irrigation régulière et maîtrisée",
                "contenu": (
                    "Adopter l'irrigation goutte-à-goutte pour économiser l'eau et réduire les maladies foliaires. "
                    "Arroser en bas volume mais fréquemment ; éviter de mouiller le feuillage. "
                    "Réduire l'arrosage 10 jours avant la récolte pour améliorer la qualité des fruits."
                ),
                "priorite": 1,
                "mois_applicable": [10, 11, 12, 1, 2, 3],
            },
            {
                "zone_agro": None,
                "categorie_reco": "Protection phytosanitaire",
                "titre": "Surveillance Tuta absoluta dès la pépinière",
                "contenu": (
                    "Installer des pièges à phéromones dès la mise en place (1 piège/ha). "
                    "Inspecter hebdomadairement la face inférieure des feuilles. "
                    "Intervenir au premier signe avec Décis ou Lambdacyhalothrine ; alterner les matières actives."
                ),
                "priorite": 2,
                "mois_applicable": [10, 11, 12, 1, 2, 3, 4],
            },
            {
                "zone_agro": None,
                "categorie_reco": "Fertilisation",
                "titre": "Apport fractionné de potassium en fructification",
                "contenu": (
                    "Augmenter les apports en K2O à partir de la nouaison (100 kg/ha KCl). "
                    "Compléter avec du nitrate de calcium pour prévenir la nécrose apicale. "
                    "Réaliser des analyses foliaires en cas de symptômes de carence."
                ),
                "priorite": 3,
                "mois_applicable": [11, 12, 1, 2],
            },
        ],
    },

    # ─────────────────────────────────────────────────────────────────────────
    # 2. OIGNON
    # ─────────────────────────────────────────────────────────────────────────
    {
        "nom": "Oignon",
        "nom_scientifique": "Allium cepa",
        "nom_local": "Seef (Wolof)",
        "famille": "Amaryllidaceae",
        "categorie": "maraichage",
        "icone": "🧅",
        "description": (
            "L'oignon est la première culture maraîchère de rente au Sénégal, "
            "avec les Niayes comme principal bassin de production. "
            "Il est cultivé en saison fraîche pour la consommation locale et l'exportation vers les pays de la sous-région."
        ),
        "parametres_climatiques": {
            "temp_min_c": 10.0,
            "temp_opt_min_c": 15.0,
            "temp_opt_max_c": 24.0,
            "temp_max_c": 32.0,
            "pluvio_min_mm": 300,
            "pluvio_opt_mm": 500,
            "pluvio_max_mm": 900,
            "ph_min": 6.0,
            "ph_opt_min": 6.2,
            "ph_opt_max": 6.8,
            "ph_max": 7.5,
            "texture_preferee": "Limono-sableuse, bien drainée et légère",
            "ensoleillement_h": 10.0,
        },
        "varietes": [
            {
                "nom": "Violet de Galmi",
                "origine": "Niger (adapté Afrique de l'Ouest)",
                "cycle_min_jours": 90,
                "cycle_max_jours": 120,
                "precocite": "Mi-saison",
                "tolerance_secheresse": True,
                "tolerance_salinite": False,
                "zones_adaptees": ["niayes", "vallee_fleuve", "bassin_arachidier"],
                "rendement_potentiel_t_ha": 25.0,
                "notes": "Variété de référence au Sénégal, bulbes violet foncé très appréciés sur les marchés locaux.",
            },
            {
                "nom": "Texas Grano 502",
                "origine": "USA, adapté Sénégal",
                "cycle_min_jours": 100,
                "cycle_max_jours": 130,
                "precocite": "Mi-saison à tardive",
                "tolerance_secheresse": False,
                "tolerance_salinite": True,
                "zones_adaptees": ["niayes", "vallee_fleuve"],
                "rendement_potentiel_t_ha": 30.0,
                "notes": "Bulbes jaunes de gros calibre, bonne conservation, adapté à la culture irriguée des Niayes.",
            },
            {
                "nom": "Safari F1",
                "origine": "Bejo / Pays-Bas",
                "cycle_min_jours": 110,
                "cycle_max_jours": 140,
                "precocite": "Tardive",
                "tolerance_secheresse": False,
                "tolerance_salinite": True,
                "zones_adaptees": ["niayes", "vallee_fleuve"],
                "rendement_potentiel_t_ha": 40.0,
                "notes": "Hybride F1 à très haut rendement, excellente conservation (6-8 mois), de plus en plus adopté.",
            },
            {
                "nom": "Gandiol Local",
                "origine": "Sénégal (sélection locale, région de Saint-Louis)",
                "cycle_min_jours": 90,
                "cycle_max_jours": 110,
                "precocite": "Précoce",
                "tolerance_secheresse": True,
                "tolerance_salinite": True,
                "zones_adaptees": ["vallee_fleuve", "niayes"],
                "rendement_potentiel_t_ha": 18.0,
                "notes": "Adapté aux sols salins de la zone du delta ; bonne résistance aux conditions difficiles.",
            },
        ],
        "stades": [
            {
                "ordre": 1,
                "nom_stade": "Semis en pépinière",
                "jours_debut": 0,
                "jours_fin": 7,
                "description": "Semis en lignes en pépinière ombragée ; germination en 5-7 jours.",
                "actions_cles": [
                    "Préparer des planches surélevées bien ameublies",
                    "Semer en lignes espacées de 10 cm à 1 cm de profondeur",
                    "Couvrir de paille légèrement pour maintenir l'humidité",
                    "Arroser en pluie fine 2 fois par jour",
                ],
                "indicateurs_visuels": "Levée en filaments verts fins, taux de germination >80%.",
            },
            {
                "ordre": 2,
                "nom_stade": "Croissance en pépinière",
                "jours_debut": 7,
                "jours_fin": 45,
                "description": "Développement des plants jusqu'à 20 cm de hauteur, prêts au repiquage.",
                "actions_cles": [
                    "Arroser régulièrement",
                    "Désherber manuellement",
                    "Apporter urée légère (15 kg/ha)",
                    "Traiter contre fonte des semis si nécessaire",
                ],
                "indicateurs_visuels": "Plants de 20-25 cm à 3-4 feuilles, tige de la grosseur d'un crayon.",
            },
            {
                "ordre": 3,
                "nom_stade": "Repiquage et installation",
                "jours_debut": 45,
                "jours_fin": 60,
                "description": "Repiquage à l'écartement 15x10 cm ; les plants s'installent en 10-15 jours.",
                "actions_cles": [
                    "Repiquer à 3-5 cm de profondeur maximum",
                    "Arroser immédiatement et les jours suivants",
                    "Appliquer fumure de fond (TSP 100 kg/ha)",
                    "Démarrer le désherbage précoce",
                ],
                "indicateurs_visuels": "Feuilles dressées et vert vif signe de bonne reprise.",
            },
            {
                "ordre": 4,
                "nom_stade": "Croissance végétative active",
                "jours_debut": 60,
                "jours_fin": 90,
                "description": "Développement foliaire intense ; les feuilles tubulaires s'accumulent.",
                "actions_cles": [
                    "Apporter azote fractionné (urée 50 kg/ha x 2)",
                    "Biner et désherber régulièrement",
                    "Surveiller les thrips (insectes ravageurs numéro 1 de l'oignon)",
                    "Maintenir irrigation tous les 3-4 jours",
                ],
                "indicateurs_visuels": "Feuilles tubulaires vert vif nombreuses, sol propre.",
            },
            {
                "ordre": 5,
                "nom_stade": "Grossissement du bulbe",
                "jours_debut": 90,
                "jours_fin": 120,
                "description": "Formation et grossissement du bulbe ; les glucides s'accumulent.",
                "actions_cles": [
                    "Apporter potassium (KCl 60 kg/ha)",
                    "Réduire progressivement l'azote",
                    "Surveiller mildiou et alternariose",
                    "Maintenir désherbage",
                ],
                "indicateurs_visuels": "Bulbes visibles au sol, feuilles commençant à se courber.",
            },
            {
                "ordre": 6,
                "nom_stade": "Maturité et récolte",
                "jours_debut": 120,
                "jours_fin": 150,
                "description": "Les feuilles versent spontanément ; arrêt de l'irrigation 10-15 jours avant récolte.",
                "actions_cles": [
                    "Arrêter l'irrigation 10-15 jours avant récolte",
                    "Récolter quand 50-80% des feuilles sont versées",
                    "Laisser sécher les bulbes au champ 3-5 jours",
                    "Conditionner en caisses aérées pour conservation",
                ],
                "indicateurs_visuels": "Feuilles versées, bulbes à pelures sèches et bien formées.",
            },
        ],
        "besoins_eau": [
            {
                "stade": "Pépinière",
                "besoin_mm_semaine": 25.0,
                "sensibilite": "Élevée",
                "frequence_irrigation": "2 fois par jour en fines quantités",
                "notes": "Sol frais en permanence sans engorgement.",
            },
            {
                "stade": "Installation post-repiquage",
                "besoin_mm_semaine": 40.0,
                "sensibilite": "Très élevée",
                "frequence_irrigation": "Quotidienne pendant 2 semaines",
                "notes": "Critique pour la reprise racinaire.",
            },
            {
                "stade": "Croissance végétative",
                "besoin_mm_semaine": 35.0,
                "sensibilite": "Modérée",
                "frequence_irrigation": "Tous les 3-4 jours",
                "notes": "L'oignon est sensible au manque comme à l'excès d'eau.",
            },
            {
                "stade": "Grossissement bulbe",
                "besoin_mm_semaine": 45.0,
                "sensibilite": "Élevée",
                "frequence_irrigation": "Tous les 3 jours",
                "notes": "Besoin en eau maximum ; stress hydrique réduit la taille des bulbes.",
            },
            {
                "stade": "Maturation - Récolte",
                "besoin_mm_semaine": 10.0,
                "sensibilite": "Modérée (risque de pourriture)",
                "frequence_irrigation": "Stopper 10-15 jours avant récolte",
                "notes": "L'excès d'eau en fin de cycle favorise les pourritures et réduit la conservation.",
            },
        ],
        "besoins_nutritionnels": [
            {
                "stade": "Fond de plantation",
                "azote_kg_ha": 0.0,
                "phosphore_kg_ha": 100.0,
                "potassium_kg_ha": 80.0,
                "calcium_kg_ha": 25.0,
                "magnesium_kg_ha": 12.0,
                "engrais_recommandes": "TSP 200 kg/ha + fumier organique 10-12 t/ha",
                "moment_application": "15-20 jours avant repiquage, incorporé",
                "notes": "Phosphore fondamental pour le développement racinaire et la bulbification.",
            },
            {
                "stade": "Croissance végétative",
                "azote_kg_ha": 80.0,
                "phosphore_kg_ha": 20.0,
                "potassium_kg_ha": 40.0,
                "calcium_kg_ha": 15.0,
                "magnesium_kg_ha": 8.0,
                "engrais_recommandes": "Urée 175 kg/ha en 2 apports (J+20 et J+40 repiquage)",
                "moment_application": "J+20 et J+40 après repiquage",
                "notes": "Fractionner l'urée pour limiter les pertes par volatilisation.",
            },
            {
                "stade": "Bulbification",
                "azote_kg_ha": 30.0,
                "phosphore_kg_ha": 0.0,
                "potassium_kg_ha": 80.0,
                "calcium_kg_ha": 20.0,
                "magnesium_kg_ha": 10.0,
                "engrais_recommandes": "KCl 130 kg/ha, sulfate de magnésium si carence",
                "moment_application": "Début bulbification visible",
                "notes": "Potassium améliore la conservation des bulbes et leur qualité commerciale.",
            },
        ],
        "calendriers": [
            {
                "zone_agro": "niayes",
                "saison": "Saison fraîche principale",
                "mois_semis_debut": 10,
                "mois_semis_fin": 11,
                "mois_recolte_debut": 2,
                "mois_recolte_fin": 4,
                "remarques": "Zone de production principale du Sénégal ; semis en octobre-novembre, récolte de février à avril.",
            },
            {
                "zone_agro": "vallee_fleuve",
                "saison": "Contre-saison froide",
                "mois_semis_debut": 10,
                "mois_semis_fin": 12,
                "mois_recolte_debut": 2,
                "mois_recolte_fin": 5,
                "remarques": "Production importante dans la zone de Podor et Saint-Louis sous irrigation.",
            },
        ],
        "rendements": [
            {
                "zone_agro": None,
                "pratique": "Traditionnel sans intrants améliorés",
                "rendement_min_t_ha": 8.0,
                "rendement_max_t_ha": 15.0,
                "rendement_moyen_t_ha": 12.0,
                "unite": "t/ha",
                "source": "ANCAR / DPA Sénégal",
                "annee_reference": 2022,
            },
            {
                "zone_agro": None,
                "pratique": "Intensif avec variétés améliorées et intrants",
                "rendement_min_t_ha": 20.0,
                "rendement_max_t_ha": 40.0,
                "rendement_moyen_t_ha": 28.0,
                "unite": "t/ha",
                "source": "ISRA Horticulture Camberene",
                "annee_reference": 2023,
            },
        ],
        "maladies": [
            {
                "nom": "Mildiou de l'oignon",
                "nom_scientifique": "Peronospora destructor",
                "pathogene_type": "Oomycète",
                "symptomes": "Duvet violacé sur feuilles, jaunissement et affaissement des fanes, bulbes de petite taille.",
                "conditions_favorables": "Humidité élevée, températures fraîches (12-18°C), brouillard des Niayes.",
                "frequence": "Fréquente en saison fraîche",
                "gravite": "Élevée",
                "stade_sensible": "Croissance végétative - Bulbification",
                "pertes_estimees": "20-50%",
                "prevention": "Éviter l'excès d'humidité, espacer les plants, détruire les résidus.",
                "traitement": "Mancozèbe 2,5 kg/ha, Chlorothalonil 2 L/ha tous les 7-10 jours.",
            },
            {
                "nom": "Fonte des semis",
                "nom_scientifique": "Pythium spp. / Rhizoctonia solani",
                "pathogene_type": "Champignon",
                "symptomes": "Pourriture du collet des jeunes plants en pépinière, effondrement et mort rapide.",
                "conditions_favorables": "Sol trop humide, températures fraîches, densité de semis élevée.",
                "frequence": "Fréquente en pépinière",
                "gravite": "Élevée en pépinière",
                "stade_sensible": "Pépinière",
                "pertes_estimees": "10-40% des plants en pépinière",
                "prevention": "Substrat sain et bien drainé, rotation des planches de pépinière.",
                "traitement": "Mancozèbe en drench, sulfate de cuivre 0,1% en arrosage préventif.",
            },
            {
                "nom": "Pourriture du collet (Botrytis)",
                "nom_scientifique": "Botrytis allii",
                "pathogene_type": "Champignon",
                "symptomes": "Pourriture molle grisâtre du collet et des bulbes, moisissure grise, odeur nauséabonde.",
                "conditions_favorables": "Humidité élevée à la récolte, blessures mécaniques, mauvaise aération.",
                "frequence": "Fréquente",
                "gravite": "Élevée (surtout en conservation)",
                "stade_sensible": "Maturation - Conservation",
                "pertes_estimees": "15-30% en conservation",
                "prevention": "Séchage soigné des bulbes, bonne aération du stockage, récolte par temps sec.",
                "traitement": "Chlorothalonil 2 L/ha en préventif avant récolte, bonne ventilation du stock.",
            },
            {
                "nom": "Alternariose",
                "nom_scientifique": "Alternaria porri",
                "pathogene_type": "Champignon",
                "symptomes": "Taches ovales brun-violacé sur les feuilles, entourées d'un halo jaune, dessèchement.",
                "conditions_favorables": "Temps chaud et humide, plantes stressées ou carencées.",
                "frequence": "Modérément fréquente",
                "gravite": "Modérée",
                "stade_sensible": "Bulbification",
                "pertes_estimees": "10-20%",
                "prevention": "Fertilisation équilibrée, éviter l'excès d'azote.",
                "traitement": "Mancozèbe 2 kg/ha, Chlorothalonil à dose homologuée.",
            },
        ],
        "ravageurs": [
            {
                "nom": "Thrips de l'oignon",
                "nom_scientifique": "Thrips tabaci",
                "type_ravageur": "Insecte piqueur-suceur (Thysanoptère)",
                "description": "Minuscules insectes jaunâtres de 1 mm, se nichent entre les feuilles.",
                "symptomes_degats": "Feuilles argentées avec points blancs, déformation et dessèchement des fanes, transmission de virus.",
                "frequence": "Très fréquente, ravageur numéro 1 de l'oignon",
                "gravite": "Très élevée",
                "stade_sensible": "Toute la culture",
                "pertes_estimees": "20-60%",
                "prevention": "Irrigation adéquate (les thrips prolifèrent en sec), pièges bleus engluants.",
                "lutte": "Confidor (imidaclopride) 0,5 L/ha, Décis 2,5 EC 0,5 L/ha, Actellic 50 EC.",
            },
            {
                "nom": "Mouche de l'oignon",
                "nom_scientifique": "Delia antiqua",
                "type_ravageur": "Insecte (Diptère)",
                "description": "Larves blanchâtres qui minent les bulbes et les tiges.",
                "symptomes_degats": "Galeries dans les bulbes, pourriture, jaunissement et mort des plants.",
                "frequence": "Modérément fréquente",
                "gravite": "Modérée à élevée",
                "stade_sensible": "Repiquage - Grossissement bulbe",
                "pertes_estimees": "10-25%",
                "prevention": "Rotation culturale, enfouissement des résidus, traitement du sol.",
                "lutte": "Actellic 50 EC, Chlorpyrifos au collet au repiquage.",
            },
            {
                "nom": "Nématodes",
                "nom_scientifique": "Ditylenchus dipsaci",
                "type_ravageur": "Nématode",
                "description": "Nématode des bulbes, particulièrement problématique dans les sols des Niayes.",
                "symptomes_degats": "Plantes rabougries, bulbes déformés et pourris, zones nécrotiques.",
                "frequence": "Fréquente dans les Niayes",
                "gravite": "Élevée",
                "stade_sensible": "Toute la culture",
                "pertes_estimees": "15-40%",
                "prevention": "Rotation culturale longue, solarisation, utilisation de plants sains.",
                "lutte": "Plantes pièges (Crotalaria), solarisation du sol, nématicides autorisés.",
            },
        ],
        "recommandations": [
            {
                "zone_agro": None,
                "categorie_reco": "Post-récolte",
                "titre": "Séchage et conservation des bulbes",
                "contenu": (
                    "Arrêter l'irrigation 10-15 jours avant récolte. "
                    "Laisser sécher les bulbes au champ 3-5 jours (feuilles vers le bas). "
                    "Stocker dans des hangars bien ventilés sur des claies en lattes ; "
                    "contrôler mensuellement et éliminer les bulbes pourris."
                ),
                "priorite": 1,
                "mois_applicable": [2, 3, 4, 5],
            },
            {
                "zone_agro": None,
                "categorie_reco": "Protection phytosanitaire",
                "titre": "Lutte préventive contre les thrips",
                "contenu": (
                    "Installer des pièges bleus engluants dès la reprise (1/100 m²). "
                    "Intervenir au seuil de 5-10 thrips par plante. "
                    "Alterner Confidor et Décis pour éviter les résistances ; "
                    "respecter les délais avant récolte."
                ),
                "priorite": 2,
                "mois_applicable": [11, 12, 1, 2, 3],
            },
            {
                "zone_agro": None,
                "categorie_reco": "Agronomie",
                "titre": "Rotation et gestion des sols dans les Niayes",
                "contenu": (
                    "Pratiquer une rotation minimale de 2 ans entre deux cultures d'oignon sur la même parcelle. "
                    "Alterner avec des céréales ou des légumineuses pour réduire les nématodes et les pathogènes du sol."
                ),
                "priorite": 3,
                "mois_applicable": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
            },
        ],
    },

    # ─────────────────────────────────────────────────────────────────────────
    # 3. PIMENT
    # ─────────────────────────────────────────────────────────────────────────
    {
        "nom": "Piment",
        "nom_scientifique": "Capsicum frutescens / Capsicum annuum",
        "nom_local": "Kaani (Wolof)",
        "famille": "Solanaceae",
        "categorie": "maraichage",
        "icone": "🌶️",
        "description": (
            "Le piment est une culture maraîchère très importante au Sénégal, "
            "cultivé à la fois pour la consommation locale (thiéboudienne) et pour l'exportation. "
            "Il tolère la chaleur sénégalaise et peut être cultivé en plusieurs saisons."
        ),
        "parametres_climatiques": {
            "temp_min_c": 15.0,
            "temp_opt_min_c": 20.0,
            "temp_opt_max_c": 30.0,
            "temp_max_c": 38.0,
            "pluvio_min_mm": 400,
            "pluvio_opt_mm": 700,
            "pluvio_max_mm": 1100,
            "ph_min": 5.5,
            "ph_opt_min": 6.0,
            "ph_opt_max": 6.8,
            "ph_max": 7.5,
            "texture_preferee": "Limono-sableuse bien drainée, riche en matière organique",
            "ensoleillement_h": 8.0,
        },
        "varietes": [
            {
                "nom": "Demon F1",
                "origine": "Syngenta / adapté Afrique",
                "cycle_min_jours": 90,
                "cycle_max_jours": 120,
                "precocite": "Précoce",
                "tolerance_secheresse": False,
                "tolerance_salinite": False,
                "zones_adaptees": ["niayes", "bassin_arachidier", "casamance"],
                "rendement_potentiel_t_ha": 18.0,
                "notes": "Piment fort très apprécié sur les marchés sénégalais, bonne résistance aux virus.",
            },
            {
                "nom": "Yolo Wonder",
                "origine": "USA, large diffusion internationale",
                "cycle_min_jours": 100,
                "cycle_max_jours": 130,
                "precocite": "Mi-saison",
                "tolerance_secheresse": False,
                "tolerance_salinite": False,
                "zones_adaptees": ["niayes", "vallee_fleuve", "senegal_oriental"],
                "rendement_potentiel_t_ha": 20.0,
                "notes": "Poivron doux-piquant, populaire pour la consommation fraîche et la transformation.",
            },
            {
                "nom": "Piment Local Sénégal (Sobanane)",
                "origine": "Sénégal (sélection paysanne)",
                "cycle_min_jours": 110,
                "cycle_max_jours": 150,
                "precocite": "Tardive",
                "tolerance_secheresse": True,
                "tolerance_salinite": True,
                "zones_adaptees": ["niayes", "bassin_arachidier", "casamance", "senegal_oriental"],
                "rendement_potentiel_t_ha": 10.0,
                "notes": "Très piquant, rustique, adapté aux conditions locales, prisé pour la sauce yassa.",
            },
            {
                "nom": "California Wonder",
                "origine": "USA",
                "cycle_min_jours": 95,
                "cycle_max_jours": 125,
                "precocite": "Mi-saison",
                "tolerance_secheresse": False,
                "tolerance_salinite": False,
                "zones_adaptees": ["niayes", "vallee_fleuve"],
                "rendement_potentiel_t_ha": 22.0,
                "notes": "Poivron carré de grande taille, destiné aux restaurants et à l'export.",
            },
        ],
        "stades": [
            {
                "ordre": 1,
                "nom_stade": "Pépinière",
                "jours_debut": 0,
                "jours_fin": 10,
                "description": "Semis en pépinière ombragée ; germination lente en 7-10 jours.",
                "actions_cles": [
                    "Semer sur substrat léger et stérilisé",
                    "Maintenir humidité constante",
                    "Protéger du plein soleil et du vent",
                    "Traitement préventif fongicide (Mancozèbe) à la levée",
                ],
                "indicateurs_visuels": "Levée des cotylédons verts, taux de germination >70%.",
            },
            {
                "ordre": 2,
                "nom_stade": "Croissance en pépinière",
                "jours_debut": 10,
                "jours_fin": 40,
                "description": "Développement des feuilles vraies ; plants à 5-6 feuilles prêts pour le repiquage.",
                "actions_cles": [
                    "Arroser quotidiennement",
                    "Apporter NPK de démarrage 12-24-12",
                    "Désherber manuellement",
                    "Surveiller fonte des semis et pucerons",
                ],
                "indicateurs_visuels": "Plants de 10-15 cm, 5-6 feuilles, tige bien robuste.",
            },
            {
                "ordre": 3,
                "nom_stade": "Repiquage et établissement",
                "jours_debut": 40,
                "jours_fin": 55,
                "description": "Repiquage en plein champ à 50x40 cm ; reprise en 7-10 jours.",
                "actions_cles": [
                    "Repiquer en soirée ou par temps couvert",
                    "Arroser copieusement après repiquage",
                    "Appliquer fumier de fond (15 t/ha)",
                    "Installer paillage pour conserver l'humidité",
                ],
                "indicateurs_visuels": "Reprise végétative, nouvelles feuilles vertes et brillantes.",
            },
            {
                "ordre": 4,
                "nom_stade": "Croissance végétative",
                "jours_debut": 55,
                "jours_fin": 80,
                "description": "Développement de la canopée ; formation de la structure ramifiée de la plante.",
                "actions_cles": [
                    "Apporter azote (urée 50 kg/ha)",
                    "Supprimer les premières fleurs pour favoriser la croissance",
                    "Surveiller pucerons et acariens",
                    "Désherber régulièrement",
                ],
                "indicateurs_visuels": "Plante bien ramifiée, feuilles de couleur vert foncé.",
            },
            {
                "ordre": 5,
                "nom_stade": "Floraison et nouaison",
                "jours_debut": 80,
                "jours_fin": 110,
                "description": "Floraison abondante ; stade critique pour le rendement.",
                "actions_cles": [
                    "Apporter potassium et bore (fertilisation foliaire)",
                    "Maintenir irrigation régulière",
                    "Éviter les fortes chaleurs (>35°C) qui stérilisent le pollen",
                    "Surveiller anthracnose sur fruits",
                ],
                "indicateurs_visuels": "Fleurs blanches abondantes, premiers petits fruits noués.",
            },
            {
                "ordre": 6,
                "nom_stade": "Fructification et récoltes échelonnées",
                "jours_debut": 110,
                "jours_fin": 150,
                "description": "Récoltes successives sur 4-8 semaines selon la variété.",
                "actions_cles": [
                    "Récolter à intervalle de 7-10 jours",
                    "Apporter engrais de couverture après chaque récolte",
                    "Surveiller anthracnose (fruits pourris)",
                    "Maintenir irrigation régulière",
                ],
                "indicateurs_visuels": "Fruits à la coloration voulue (vert, jaune, rouge selon usage).",
            },
        ],
        "besoins_eau": [
            {
                "stade": "Pépinière",
                "besoin_mm_semaine": 20.0,
                "sensibilite": "Élevée",
                "frequence_irrigation": "2 fois par jour",
                "notes": "Sol frais sans engorgement.",
            },
            {
                "stade": "Repiquage - Établissement",
                "besoin_mm_semaine": 35.0,
                "sensibilite": "Très élevée",
                "frequence_irrigation": "Quotidienne",
                "notes": "Arrosage abondant les 10 premiers jours.",
            },
            {
                "stade": "Croissance végétative",
                "besoin_mm_semaine": 40.0,
                "sensibilite": "Modérée",
                "frequence_irrigation": "Tous les 2-3 jours",
                "notes": "Le piment tolère légèrement le stress hydrique hors floraison.",
            },
            {
                "stade": "Floraison",
                "besoin_mm_semaine": 45.0,
                "sensibilite": "Très élevée",
                "frequence_irrigation": "Tous les 2 jours",
                "notes": "Stress à la floraison entraîne chute des fleurs et réduction des rendements.",
            },
            {
                "stade": "Fructification",
                "besoin_mm_semaine": 50.0,
                "sensibilite": "Élevée",
                "frequence_irrigation": "Tous les 2-3 jours",
                "notes": "Maintenir humidité régulière pour éviter la pourriture apicale.",
            },
        ],
        "besoins_nutritionnels": [
            {
                "stade": "Fond de plantation",
                "azote_kg_ha": 0.0,
                "phosphore_kg_ha": 80.0,
                "potassium_kg_ha": 60.0,
                "calcium_kg_ha": 25.0,
                "magnesium_kg_ha": 12.0,
                "engrais_recommandes": "Fumier organique 15 t/ha + TSP 175 kg/ha",
                "moment_application": "10-15 jours avant repiquage",
                "notes": "Bien décomposer le fumier avant application.",
            },
            {
                "stade": "Croissance végétative",
                "azote_kg_ha": 70.0,
                "phosphore_kg_ha": 20.0,
                "potassium_kg_ha": 50.0,
                "calcium_kg_ha": 20.0,
                "magnesium_kg_ha": 10.0,
                "engrais_recommandes": "NPK 15-15-15 (200 kg/ha) + urée",
                "moment_application": "J+20 et J+40 après repiquage",
                "notes": "Éviter l'excès d'azote qui favorise les feuilles au détriment des fruits.",
            },
            {
                "stade": "Floraison - Fructification",
                "azote_kg_ha": 40.0,
                "phosphore_kg_ha": 10.0,
                "potassium_kg_ha": 90.0,
                "calcium_kg_ha": 30.0,
                "magnesium_kg_ha": 15.0,
                "engrais_recommandes": "KCl 150 kg/ha + nitrate de calcium + bore foliaire",
                "moment_application": "Début floraison",
                "notes": "Le bore améliore la nouaison ; le calcium prévient la pourriture apicale.",
            },
        ],
        "calendriers": [
            {
                "zone_agro": "niayes",
                "saison": "Saison fraîche",
                "mois_semis_debut": 10,
                "mois_semis_fin": 12,
                "mois_recolte_debut": 2,
                "mois_recolte_fin": 5,
                "remarques": "Meilleure qualité des fruits en saison fraîche.",
            },
            {
                "zone_agro": "niayes",
                "saison": "Saison chaude",
                "mois_semis_debut": 3,
                "mois_semis_fin": 5,
                "mois_recolte_debut": 6,
                "mois_recolte_fin": 9,
                "remarques": "Possible mais rendements moindres ; risque de chute des fleurs par chaleur.",
            },
            {
                "zone_agro": "casamance",
                "saison": "Hivernage / Saison des pluies",
                "mois_semis_debut": 6,
                "mois_semis_fin": 7,
                "mois_recolte_debut": 9,
                "mois_recolte_fin": 12,
                "remarques": "Culture sous pluies naturelles possible en Casamance avec drainage.",
            },
        ],
        "rendements": [
            {
                "zone_agro": None,
                "pratique": "Traditionnel",
                "rendement_min_t_ha": 5.0,
                "rendement_max_t_ha": 10.0,
                "rendement_moyen_t_ha": 7.0,
                "unite": "t/ha",
                "source": "ANCAR Sénégal",
                "annee_reference": 2022,
            },
            {
                "zone_agro": None,
                "pratique": "Amélioré avec variétés hybrides",
                "rendement_min_t_ha": 12.0,
                "rendement_max_t_ha": 25.0,
                "rendement_moyen_t_ha": 18.0,
                "unite": "t/ha",
                "source": "ISRA Horticulture",
                "annee_reference": 2023,
            },
        ],
        "maladies": [
            {
                "nom": "Anthracnose du piment",
                "nom_scientifique": "Colletotrichum gloeosporioides / C. capsici",
                "pathogene_type": "Champignon",
                "symptomes": "Taches brunes déprimées sur fruits, à centre orangé (sporulation), pourriture des fruits mûrs.",
                "conditions_favorables": "Températures chaudes (25-30°C), humidité élevée, blessures sur fruits.",
                "frequence": "Très fréquente",
                "gravite": "Très élevée",
                "stade_sensible": "Fructification - Maturation",
                "pertes_estimees": "20-60% des fruits",
                "prevention": "Variétés tolérantes, éviter blessures, ramassage régulier des fruits.",
                "traitement": "Mancozèbe 2,5 kg/ha, Chlorothalonil 2 L/ha, sulfate de cuivre 3 kg/ha.",
            },
            {
                "nom": "Flétrissement bactérien",
                "nom_scientifique": "Ralstonia solanacearum",
                "pathogene_type": "Bactérie",
                "symptomes": "Flétrissement brutal et irréversible, vasculaire bruni, plants morts rapidement.",
                "conditions_favorables": "Sols chauds et humides, blessures racinaires, monoculture de solanacées.",
                "frequence": "Fréquente",
                "gravite": "Très élevée",
                "stade_sensible": "Croissance végétative - Fructification",
                "pertes_estimees": "20-80%",
                "prevention": "Rotation avec céréales, variétés tolérantes, greffage sur porte-greffe résistant.",
                "traitement": "Pas de traitement curatif ; arracher et brûler les plants atteints.",
            },
            {
                "nom": "Pourriture apicale",
                "nom_scientifique": "Désordre physiologique (carence Ca)",
                "pathogene_type": "Physiologique",
                "symptomes": "Tache noire déprimée à l'apex des fruits, tissus nécrosés, fruits difformes.",
                "conditions_favorables": "Stress hydrique, carence en calcium, excès d'azote ou de potassium.",
                "frequence": "Fréquente",
                "gravite": "Modérée à élevée",
                "stade_sensible": "Fructification",
                "pertes_estimees": "10-25%",
                "prevention": "Irrigation régulière, apport de nitrate de calcium.",
                "traitement": "Pulvérisation foliaire de nitrate de calcium (0,4%) à la floraison.",
            },
            {
                "nom": "Viroses (CMV, PVY)",
                "nom_scientifique": "Cucumber Mosaic Virus / Potato Virus Y",
                "pathogene_type": "Virus",
                "symptomes": "Mosaïque, déformation des feuilles, nanisme, fruits déformés et de mauvaise qualité.",
                "conditions_favorables": "Présence de pucerons vecteurs, culture à proximité d'autres solanacées.",
                "frequence": "Fréquente",
                "gravite": "Élevée",
                "stade_sensible": "Toute la culture",
                "pertes_estimees": "15-40%",
                "prevention": "Contrôler les pucerons, utiliser des semences certifiées, détruire les plants malades.",
                "traitement": "Pas de traitement curatif ; lutter contre les vecteurs (Confidor, Décis).",
            },
        ],
        "ravageurs": [
            {
                "nom": "Pucerons",
                "nom_scientifique": "Aphis gossypii / Myzus persicae",
                "type_ravageur": "Insecte piqueur-suceur",
                "description": "Colonies denses de pucerons verts sous les feuilles et sur les jeunes pousses.",
                "symptomes_degats": "Déformation des jeunes pousses, miellat, fumagine, transmission de virus.",
                "frequence": "Très fréquente",
                "gravite": "Élevée (principalement vecteur viral)",
                "stade_sensible": "Toute la culture",
                "pertes_estimees": "10-30%",
                "prevention": "Pièges jaunes, insectes auxiliaires, éliminer les plantes-hôtes.",
                "lutte": "Confidor 0,5 L/ha, Cypermethrine 0,5 L/ha, savon insecticide.",
            },
            {
                "nom": "Acariens",
                "nom_scientifique": "Polyphagotarsonemus latus / Tetranychus urticae",
                "type_ravageur": "Acarien",
                "description": "Minuscules acariens invisibles à l'œil nu, particulièrement actifs en saison sèche.",
                "symptomes_degats": "Déformation des feuilles, aspect huileux et bronzé, nanisme des pousses terminales.",
                "frequence": "Fréquente en saison chaude",
                "gravite": "Élevée",
                "stade_sensible": "Végétation - Floraison",
                "pertes_estimees": "15-30%",
                "prevention": "Irrigation adéquate, éviter conditions sèches prolongées.",
                "lutte": "Actellic 50 EC 1 L/ha, soufre mouillable, huile de neem.",
            },
            {
                "nom": "Chenilles de la capsule",
                "nom_scientifique": "Helicoverpa armigera",
                "type_ravageur": "Insecte défoliateur (Lépidoptère)",
                "description": "Chenilles polyphages qui percent et pénètrent dans les fruits du piment.",
                "symptomes_degats": "Galeries dans les fruits, pourriture secondaire, fruits tombés.",
                "frequence": "Fréquente",
                "gravite": "Élevée",
                "stade_sensible": "Fructification",
                "pertes_estimees": "15-35%",
                "prevention": "Pièges à phéromones, ramassage des fruits attaqués.",
                "lutte": "Décis 2,5 EC 0,5 L/ha, Lambdacyhalothrine 0,3 L/ha.",
            },
        ],
        "recommandations": [
            {
                "zone_agro": None,
                "categorie_reco": "Protection phytosanitaire",
                "titre": "Programme de lutte contre l'anthracnose",
                "contenu": (
                    "Traiter préventivement avec Mancozèbe (2,5 kg/ha) dès la nouaison, "
                    "tous les 10-14 jours. Alterner avec Chlorothalonil. "
                    "Ramasser et détruire les fruits atteints immédiatement."
                ),
                "priorite": 1,
                "mois_applicable": [11, 12, 1, 2, 3, 4, 5],
            },
            {
                "zone_agro": None,
                "categorie_reco": "Agronomie",
                "titre": "Éviter l'excès d'azote",
                "contenu": (
                    "Un excès d'azote favorise le développement végétatif au détriment de la floraison et "
                    "de la fructification. Fractionner les apports et privilégier le potassium à partir de la floraison."
                ),
                "priorite": 2,
                "mois_applicable": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
            },
        ],
    },

    # ─────────────────────────────────────────────────────────────────────────
    # 4. GOMBO
    # ─────────────────────────────────────────────────────────────────────────
    {
        "nom": "Gombo",
        "nom_scientifique": "Abelmoschus esculentus",
        "nom_local": "Kanja (Wolof)",
        "famille": "Malvaceae",
        "categorie": "maraichage",
        "icone": "🫛",
        "description": (
            "Le gombo est une culture maraîchère très répandue au Sénégal, "
            "appréciée dans la cuisine locale (sauce kanja). "
            "Rustique et tolérant la chaleur, il se cultive en hivernage comme en saison sèche irriguée dans tout le pays."
        ),
        "parametres_climatiques": {
            "temp_min_c": 18.0,
            "temp_opt_min_c": 24.0,
            "temp_opt_max_c": 35.0,
            "temp_max_c": 42.0,
            "pluvio_min_mm": 400,
            "pluvio_opt_mm": 700,
            "pluvio_max_mm": 1200,
            "ph_min": 5.8,
            "ph_opt_min": 6.0,
            "ph_opt_max": 6.8,
            "ph_max": 7.5,
            "texture_preferee": "Limoneuse à limono-argileuse, bien drainée",
            "ensoleillement_h": 8.0,
        },
        "varietes": [
            {
                "nom": "Clemson Spineless",
                "origine": "USA, très répandu en Afrique de l'Ouest",
                "cycle_min_jours": 55,
                "cycle_max_jours": 70,
                "precocite": "Précoce",
                "tolerance_secheresse": True,
                "tolerance_salinite": False,
                "zones_adaptees": ["niayes", "bassin_arachidier", "vallee_fleuve", "casamance"],
                "rendement_potentiel_t_ha": 12.0,
                "notes": "Variété sans épines très populaire, fonds vert clair, largement cultivée au Sénégal.",
            },
            {
                "nom": "Pakia Local",
                "origine": "Sénégal (sélection locale)",
                "cycle_min_jours": 60,
                "cycle_max_jours": 80,
                "precocite": "Mi-saison",
                "tolerance_secheresse": True,
                "tolerance_salinite": True,
                "zones_adaptees": ["bassin_arachidier", "senegal_oriental", "casamance", "zone_sylvopastorale"],
                "rendement_potentiel_t_ha": 8.0,
                "notes": "Variété locale rustique bien adaptée aux conditions difficiles du Sahel sénégalais.",
            },
            {
                "nom": "Perkins Long Pod",
                "origine": "International",
                "cycle_min_jours": 55,
                "cycle_max_jours": 70,
                "precocite": "Précoce",
                "tolerance_secheresse": False,
                "tolerance_salinite": False,
                "zones_adaptees": ["niayes", "vallee_fleuve", "casamance"],
                "rendement_potentiel_t_ha": 14.0,
                "notes": "Gousses longues (12-15 cm), bonne productivité, adapté à la culture irriguée.",
            },
            {
                "nom": "Kirikou F1",
                "origine": "Syngenta / Afrique",
                "cycle_min_jours": 50,
                "cycle_max_jours": 65,
                "precocite": "Très précoce",
                "tolerance_secheresse": False,
                "tolerance_salinite": False,
                "zones_adaptees": ["niayes", "vallee_fleuve"],
                "rendement_potentiel_t_ha": 18.0,
                "notes": "Hybride F1 très productif, gousses vert foncé, récoltes intenses sur courte période.",
            },
        ],
        "stades": [
            {
                "ordre": 1,
                "nom_stade": "Germination",
                "jours_debut": 0,
                "jours_fin": 7,
                "description": "Semis direct en poquet ; germination en 5-7 jours si sol chaud.",
                "actions_cles": [
                    "Scarifier ou tremper les graines 12h avant semis",
                    "Semer 3-4 graines par poquet à 3 cm de profondeur",
                    "Arroser immédiatement après semis",
                    "Sol bien ameubli et humide",
                ],
                "indicateurs_visuels": "Cotylédons émergeant du sol, levée uniforme.",
            },
            {
                "ordre": 2,
                "nom_stade": "Plantule",
                "jours_debut": 7,
                "jours_fin": 20,
                "description": "Développement des premières feuilles vraies ; démariage à 1-2 plants.",
                "actions_cles": [
                    "Démarier à 1-2 plants vigoureux par poquet",
                    "Premier binage léger",
                    "Arroser tous les 2 jours",
                    "Surveiller fonte des semis et pucerons",
                ],
                "indicateurs_visuels": "2-3 feuilles vraies, plants bien dressés.",
            },
            {
                "ordre": 3,
                "nom_stade": "Croissance végétative",
                "jours_debut": 20,
                "jours_fin": 40,
                "description": "Développement rapide de la plante ; port érigé et robuste.",
                "actions_cles": [
                    "Apporter engrais NPK 15-15-15 (150 kg/ha)",
                    "Biner et désherber",
                    "Surveiller les pucerons et aleurodes",
                    "Arroser régulièrement",
                ],
                "indicateurs_visuels": "Plante de 40-60 cm, bien feuillée, couleur vert foncé.",
            },
            {
                "ordre": 4,
                "nom_stade": "Floraison",
                "jours_debut": 40,
                "jours_fin": 55,
                "description": "Apparition des grandes fleurs jaunes à cœur rouge ; floraison échelonnée.",
                "actions_cles": [
                    "Apporter potassium (KCl 60 kg/ha)",
                    "Irriguer régulièrement",
                    "Surveiller les foreurs de tiges",
                    "Désherber si nécessaire",
                ],
                "indicateurs_visuels": "Grandes fleurs jaunes à cœur pourpre, abondantes.",
            },
            {
                "ordre": 5,
                "nom_stade": "Fructification et récoltes",
                "jours_debut": 55,
                "jours_fin": 90,
                "description": "Récoltes très fréquentes toutes les 2-3 jours pour avoir des gousses tendres.",
                "actions_cles": [
                    "Récolter les gousses à 7-10 cm (tendres)",
                    "Ne pas laisser grossir les fruits (lignification rapide)",
                    "Maintenir l'irrigation régulière",
                    "Apporter engrais de couverture après 2-3 récoltes",
                ],
                "indicateurs_visuels": "Gousses vertes tendres de 7-12 cm, section ronde ou cannelée.",
            },
        ],
        "besoins_eau": [
            {
                "stade": "Germination",
                "besoin_mm_semaine": 25.0,
                "sensibilite": "Élevée",
                "frequence_irrigation": "Quotidienne",
                "notes": "Sol humide constant pour une bonne germination.",
            },
            {
                "stade": "Croissance végétative",
                "besoin_mm_semaine": 35.0,
                "sensibilite": "Modérée",
                "frequence_irrigation": "Tous les 2-3 jours",
                "notes": "Le gombo est relativement tolérant au stress hydrique.",
            },
            {
                "stade": "Floraison",
                "besoin_mm_semaine": 45.0,
                "sensibilite": "Élevée",
                "frequence_irrigation": "Tous les 2 jours",
                "notes": "Stress hydrique à la floraison cause chute des fleurs.",
            },
            {
                "stade": "Fructification",
                "besoin_mm_semaine": 40.0,
                "sensibilite": "Modérée",
                "frequence_irrigation": "Tous les 2-3 jours",
                "notes": "Maintenir humidité pour la production continue des gousses.",
            },
        ],
        "besoins_nutritionnels": [
            {
                "stade": "Fond de plantation",
                "azote_kg_ha": 0.0,
                "phosphore_kg_ha": 60.0,
                "potassium_kg_ha": 40.0,
                "calcium_kg_ha": 20.0,
                "magnesium_kg_ha": 10.0,
                "engrais_recommandes": "Fumier 10 t/ha + TSP 130 kg/ha",
                "moment_application": "Avant labour ou au semis",
                "notes": "Le gombo répond bien à la matière organique.",
            },
            {
                "stade": "Croissance végétative",
                "azote_kg_ha": 60.0,
                "phosphore_kg_ha": 15.0,
                "potassium_kg_ha": 40.0,
                "calcium_kg_ha": 15.0,
                "magnesium_kg_ha": 8.0,
                "engrais_recommandes": "NPK 15-15-15 (200 kg/ha) + urée 50 kg/ha",
                "moment_application": "J+20 et J+35 après levée",
                "notes": "Fractionner l'azote pour une meilleure efficacité.",
            },
            {
                "stade": "Fructification",
                "azote_kg_ha": 30.0,
                "phosphore_kg_ha": 0.0,
                "potassium_kg_ha": 60.0,
                "calcium_kg_ha": 15.0,
                "magnesium_kg_ha": 8.0,
                "engrais_recommandes": "KCl 100 kg/ha + sulfate de magnésium",
                "moment_application": "Début fructification puis toutes les 3 semaines",
                "notes": "Potassium pour la qualité et la productivité continue des gousses.",
            },
        ],
        "calendriers": [
            {
                "zone_agro": "niayes",
                "saison": "Saison chaude irriguée",
                "mois_semis_debut": 3,
                "mois_semis_fin": 5,
                "mois_recolte_debut": 5,
                "mois_recolte_fin": 8,
                "remarques": "Profite des températures élevées de la saison chaude.",
            },
            {
                "zone_agro": "bassin_arachidier",
                "saison": "Hivernage",
                "mois_semis_debut": 6,
                "mois_semis_fin": 7,
                "mois_recolte_debut": 8,
                "mois_recolte_fin": 10,
                "remarques": "Culture pluviale possible en hivernage dans tout le bassin arachidier.",
            },
            {
                "zone_agro": "vallee_fleuve",
                "saison": "Contre-saison chaude",
                "mois_semis_debut": 3,
                "mois_semis_fin": 6,
                "mois_recolte_debut": 5,
                "mois_recolte_fin": 9,
                "remarques": "Culture irriguée toute l'année possible dans la vallée.",
            },
        ],
        "rendements": [
            {
                "zone_agro": None,
                "pratique": "Traditionnel",
                "rendement_min_t_ha": 4.0,
                "rendement_max_t_ha": 8.0,
                "rendement_moyen_t_ha": 6.0,
                "unite": "t/ha",
                "source": "ANCAR Sénégal",
                "annee_reference": 2022,
            },
            {
                "zone_agro": None,
                "pratique": "Amélioré avec irrigation et intrants",
                "rendement_min_t_ha": 10.0,
                "rendement_max_t_ha": 20.0,
                "rendement_moyen_t_ha": 14.0,
                "unite": "t/ha",
                "source": "ISRA Dakar",
                "annee_reference": 2023,
            },
        ],
        "maladies": [
            {
                "nom": "Oïdium du gombo",
                "nom_scientifique": "Erysiphe cichoracearum / Sphaerotheca fuliginea",
                "pathogene_type": "Champignon",
                "symptomes": "Poudre blanche farineuse sur les deux faces des feuilles, jaunissement et dessèchement.",
                "conditions_favorables": "Temps sec et chaud, nuits fraîches, mauvaise aération.",
                "frequence": "Très fréquente en saison sèche",
                "gravite": "Modérée à élevée",
                "stade_sensible": "Croissance végétative - Fructification",
                "pertes_estimees": "10-30%",
                "prevention": "Espacement suffisant, bonne aération, éviter l'excès d'azote.",
                "traitement": "Soufre mouillable 3 kg/ha, Mancozèbe 2 kg/ha.",
            },
            {
                "nom": "Maladie de la jaunisse du gombo (YVMV)",
                "nom_scientifique": "Okra Yellow Vein Mosaic Virus",
                "pathogene_type": "Virus",
                "symptomes": "Jaunissement des nervures, mosaïque chlorotique, déformation des feuilles et des fruits, nanisme.",
                "conditions_favorables": "Présence de l'aleurode Bemisia tabaci (vecteur), températures élevées.",
                "frequence": "Très fréquente",
                "gravite": "Très élevée",
                "stade_sensible": "Toute la culture",
                "pertes_estimees": "30-80%",
                "prevention": "Lutter contre Bemisia tabaci, variétés tolérantes, éliminer les plants malades.",
                "traitement": "Pas de curatif ; contrôler le vecteur avec Confidor 0,5 L/ha.",
            },
            {
                "nom": "Flétrissement fusarien",
                "nom_scientifique": "Fusarium oxysporum f. sp. vasinfectum",
                "pathogene_type": "Champignon",
                "symptomes": "Flétrissement progressif, vasculaire brun à la coupe, jaunissement unilatéral.",
                "conditions_favorables": "Sols pauvres en matière organique, températures élevées, monoculture.",
                "frequence": "Modérément fréquente",
                "gravite": "Élevée",
                "stade_sensible": "Croissance végétative",
                "pertes_estimees": "15-40%",
                "prevention": "Rotation culturale, solarisation, variétés résistantes, amendement organique.",
                "traitement": "Pas de curatif efficace ; prévention et rotation.",
            },
            {
                "nom": "Pourriture des fruits",
                "nom_scientifique": "Phytophthora sp. / Pythium sp.",
                "pathogene_type": "Oomycète",
                "symptomes": "Pourriture molle et aqueuse des gousses au contact du sol, moisissures blanches.",
                "conditions_favorables": "Sol trop humide, mauvais drainage, température chaude.",
                "frequence": "Fréquente en hivernage",
                "gravite": "Modérée",
                "stade_sensible": "Fructification",
                "pertes_estimees": "10-20%",
                "prevention": "Bonne structure du sol, drainage, paillage pour éviter contact fruits-sol.",
                "traitement": "Mancozèbe 2 kg/ha en préventif.",
            },
        ],
        "ravageurs": [
            {
                "nom": "Aleurode (Mouche blanche)",
                "nom_scientifique": "Bemisia tabaci",
                "type_ravageur": "Insecte piqueur-suceur",
                "description": "Vecteur du virus YVMV, ravageur numéro 1 du gombo au Sénégal.",
                "symptomes_degats": "Jaunissement, miellat, fumagine, et surtout transmission des viroses.",
                "frequence": "Très fréquente",
                "gravite": "Très élevée (vecteur viral)",
                "stade_sensible": "Toute la culture",
                "pertes_estimees": "20-80% (via virus)",
                "prevention": "Pièges jaunes engluants, filets insect-proof, plantes-pièges.",
                "lutte": "Confidor (imidaclopride) 0,5 L/ha, Actellic 50 EC, savon insecticide.",
            },
            {
                "nom": "Foreur des tiges du gombo",
                "nom_scientifique": "Earias insulana / E. biplaga",
                "type_ravageur": "Insecte défoliateur (Lépidoptère)",
                "description": "Chenilles roses qui pénètrent dans les tiges et les fruits du gombo.",
                "symptomes_degats": "Galeries dans les tiges (verse), boutons et fruits perforés.",
                "frequence": "Fréquente",
                "gravite": "Élevée",
                "stade_sensible": "Floraison - Fructification",
                "pertes_estimees": "15-35%",
                "prevention": "Ramassage manuel, pièges à phéromones.",
                "lutte": "Cypermethrine 0,5 L/ha, Décis 2,5 EC 0,5 L/ha.",
            },
            {
                "nom": "Nématodes à galles",
                "nom_scientifique": "Meloidogyne spp.",
                "type_ravageur": "Nématode",
                "description": "Nématodes endoparasites formant des galles sur les racines.",
                "symptomes_degats": "Rabougrissement, jaunissement, galles racinaires, sensibilité accrue aux pathogènes.",
                "frequence": "Fréquente dans les sols sableux",
                "gravite": "Élevée",
                "stade_sensible": "Toute la culture",
                "pertes_estimees": "20-40%",
                "prevention": "Rotation avec céréales, solarisation, plantes antagonistes (Crotalaria).",
                "lutte": "Plantes-pièges, solarisation, nématicides autorisés.",
            },
        ],
        "recommandations": [
            {
                "zone_agro": None,
                "categorie_reco": "Récolte",
                "titre": "Récolter régulièrement pour maintenir la production",
                "contenu": (
                    "Récolter les gousses tous les 2-3 jours quand elles mesurent 7-10 cm. "
                    "Laisser vieillir les gousses réduit la production et durcit les fruits. "
                    "Les gousses dépassées doivent être éliminées même si non commercialisées."
                ),
                "priorite": 1,
                "mois_applicable": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
            },
            {
                "zone_agro": None,
                "categorie_reco": "Protection phytosanitaire",
                "titre": "Lutte préventive contre la jaunisse du gombo",
                "contenu": (
                    "Installer des pièges jaunes dès le semis pour surveiller Bemisia tabaci. "
                    "Intervenir au seuil de 5 aleurodes/plante avec Confidor. "
                    "Éliminer immédiatement les plants présentant des symptômes viraux."
                ),
                "priorite": 2,
                "mois_applicable": [3, 4, 5, 6, 7, 8, 9, 10],
            },
        ],
    },
]
