# Crops 5-8: Aubergine, Chou, Concombre, Pastèque

_AUBERGINE = {
    "nom": "Aubergine",
    "nom_scientifique": "Solanum melongena",
    "nom_local": "Jaxatu (Wolof)",
    "famille": "Solanaceae",
    "categorie": "maraichage",
    "icone": "🍆",
    "description": (
        "L'aubergine est une culture maraîchère de base au Sénégal, cultivée toute l'année sous irrigation. "
        "Elle est très consommée localement (thiou, yassa) et tolère bien la chaleur sénégalaise."
    ),
    "parametres_climatiques": {
        "temp_min_c": 15.0,
        "temp_opt_min_c": 22.0,
        "temp_opt_max_c": 32.0,
        "temp_max_c": 40.0,
        "pluvio_min_mm": 400,
        "pluvio_opt_mm": 700,
        "pluvio_max_mm": 1100,
        "ph_min": 5.5,
        "ph_opt_min": 6.0,
        "ph_opt_max": 6.8,
        "ph_max": 7.5,
        "texture_preferee": "Limono-sableuse bien drainée, riche en matière organique",
        "ensoleillement_h": 8.0,
    },
    "varietes": [
        {
            "nom": "Djaxatu Local (Aubergine locale)",
            "origine": "Sénégal (sélection paysanne)",
            "cycle_min_jours": 90,
            "cycle_max_jours": 130,
            "precocite": "Mi-saison",
            "tolerance_secheresse": True,
            "tolerance_salinite": True,
            "zones_adaptees": ["niayes", "bassin_arachidier", "casamance", "senegal_oriental"],
            "rendement_potentiel_t_ha": 15.0,
            "notes": "Aubergine locale très répandue, fruits violets petits-moyens, rustique et adaptée au climat sénégalais.",
        },
        {
            "nom": "Black Beauty",
            "origine": "USA, très répandu Afrique de l'Ouest",
            "cycle_min_jours": 85,
            "cycle_max_jours": 110,
            "precocite": "Précoce",
            "tolerance_secheresse": False,
            "tolerance_salinite": False,
            "zones_adaptees": ["niayes", "vallee_fleuve"],
            "rendement_potentiel_t_ha": 22.0,
            "notes": "Gros fruits noirs brillants, très productive, demande une bonne fertilisation.",
        },
        {
            "nom": "Kalenda F1",
            "origine": "Clause / France - adapté Afrique",
            "cycle_min_jours": 80,
            "cycle_max_jours": 100,
            "precocite": "Précoce",
            "tolerance_secheresse": False,
            "tolerance_salinite": False,
            "zones_adaptees": ["niayes", "vallee_fleuve"],
            "rendement_potentiel_t_ha": 35.0,
            "notes": "Hybride F1 très productif, fruits de qualité uniforme, bien adapté à la culture irriguée des Niayes.",
        },
        {
            "nom": "Zebrina Local",
            "origine": "Sénégal / Gambie",
            "cycle_min_jours": 95,
            "cycle_max_jours": 130,
            "precocite": "Mi-saison",
            "tolerance_secheresse": True,
            "tolerance_salinite": True,
            "zones_adaptees": ["casamance", "bassin_arachidier", "senegal_oriental"],
            "rendement_potentiel_t_ha": 12.0,
            "notes": "Fruits striés verts-violets, très appréciés localement, rustique.",
        },
    ],
    "stades": [
        {
            "ordre": 1,
            "nom_stade": "Pépinière",
            "jours_debut": 0,
            "jours_fin": 10,
            "description": "Semis en pépinière ombragée ; germination lente en 8-10 jours.",
            "actions_cles": [
                "Semer sur substrat stérilisé (mélange terreau-sable 2:1)",
                "Couvrir légèrement et maintenir l'humidité",
                "Ombrer à 50% pour éviter la brûlure des jeunes plants",
                "Traitement préventif Mancozèbe dès la levée",
            ],
            "indicateurs_visuels": "Cotylédons ovales vert-violet, taux de germination >75%.",
        },
        {
            "ordre": 2,
            "nom_stade": "Croissance en pépinière",
            "jours_debut": 10,
            "jours_fin": 35,
            "description": "Développement de 4-6 feuilles vraies ; plants de 15-20 cm prêts au repiquage.",
            "actions_cles": [
                "Arroser quotidiennement",
                "Apporter NPK de démarrage",
                "Désherber manuellement",
                "Surveiller les pucerons et aleurodes",
            ],
            "indicateurs_visuels": "Plants de 15-20 cm, 4-6 feuilles, tige bien ferme.",
        },
        {
            "ordre": 3,
            "nom_stade": "Repiquage et installation",
            "jours_debut": 35,
            "jours_fin": 50,
            "description": "Repiquage à 60x50 cm ; installation en 10-15 jours.",
            "actions_cles": [
                "Repiquer en soirée ou temps couvert",
                "Arroser copieusement après repiquage",
                "Appliquer fumier de fond (15 t/ha)",
                "Paillage recommandé pour conserver l'humidité",
            ],
            "indicateurs_visuels": "Nouvelles feuilles brillantes et dressées, signe de reprise racinaire.",
        },
        {
            "ordre": 4,
            "nom_stade": "Croissance végétative",
            "jours_debut": 50,
            "jours_fin": 75,
            "description": "Développement intense du feuillage et de la structure de la plante.",
            "actions_cles": [
                "Apporter fumure azotée (urée 50 kg/ha)",
                "Désherber et biner",
                "Surveiller acariens et foreurs",
                "Maintenir irrigation régulière",
            ],
            "indicateurs_visuels": "Plante de 50-80 cm, feuilles larges vert foncé.",
        },
        {
            "ordre": 5,
            "nom_stade": "Floraison et fructification",
            "jours_debut": 75,
            "jours_fin": 110,
            "description": "Floraison violette abondante ; formation et grossissement des fruits.",
            "actions_cles": [
                "Apporter potassium et calcium",
                "Surveiller les foreurs de fruits et acariens",
                "Maintenir irrigation régulière",
                "Effeuiller la base pour l'aération",
            ],
            "indicateurs_visuels": "Fleurs violettes, fruits verts puis violet foncé brillants.",
        },
        {
            "ordre": 6,
            "nom_stade": "Récoltes échelonnées",
            "jours_debut": 110,
            "jours_fin": 140,
            "description": "Récoltes successives sur 4-6 semaines.",
            "actions_cles": [
                "Récolter à bonne maturité (brillant, pas de graines dures)",
                "Intervalle de récolte : 7-10 jours",
                "Apporter engrais de couverture",
                "Surveiller les maladies en fin de cycle",
            ],
            "indicateurs_visuels": "Fruits brillants, fermes et à la bonne taille selon variété.",
        },
    ],
    "besoins_eau": [
        {
            "stade": "Pépinière",
            "besoin_mm_semaine": 20.0,
            "sensibilite": "Élevée",
            "frequence_irrigation": "2 fois par jour",
            "notes": "Maintenir humidité sans engorgement.",
        },
        {
            "stade": "Repiquage - Installation",
            "besoin_mm_semaine": 40.0,
            "sensibilite": "Très élevée",
            "frequence_irrigation": "Quotidienne les 2 premières semaines",
            "notes": "Arrosage abondant indispensable pour la reprise.",
        },
        {
            "stade": "Croissance végétative",
            "besoin_mm_semaine": 45.0,
            "sensibilite": "Modérée",
            "frequence_irrigation": "Tous les 2-3 jours",
            "notes": "L'aubergine tolère mieux la chaleur que la tomate.",
        },
        {
            "stade": "Floraison - Fructification",
            "besoin_mm_semaine": 55.0,
            "sensibilite": "Élevée",
            "frequence_irrigation": "Tous les 2 jours",
            "notes": "Besoins en eau maximaux ; irrégularité cause chute des fleurs.",
        },
        {
            "stade": "Récoltes",
            "besoin_mm_semaine": 40.0,
            "sensibilite": "Modérée",
            "frequence_irrigation": "Tous les 2-3 jours",
            "notes": "Maintenir productivité.",
        },
    ],
    "besoins_nutritionnels": [
        {
            "stade": "Fond de plantation",
            "azote_kg_ha": 0.0,
            "phosphore_kg_ha": 80.0,
            "potassium_kg_ha": 60.0,
            "calcium_kg_ha": 25.0,
            "magnesium_kg_ha": 12.0,
            "engrais_recommandes": "Fumier 15 t/ha + TSP 175 kg/ha",
            "moment_application": "Avant repiquage",
            "notes": "Fumier bien décomposé ; éviter le fumier frais.",
        },
        {
            "stade": "Croissance végétative",
            "azote_kg_ha": 70.0,
            "phosphore_kg_ha": 20.0,
            "potassium_kg_ha": 50.0,
            "calcium_kg_ha": 20.0,
            "magnesium_kg_ha": 10.0,
            "engrais_recommandes": "NPK 15-15-15 (200 kg/ha) + urée 100 kg/ha en 2 fois",
            "moment_application": "J+20 et J+40 après repiquage",
            "notes": "L'aubergine est une grande consommatrice d'azote.",
        },
        {
            "stade": "Floraison - Fructification",
            "azote_kg_ha": 50.0,
            "phosphore_kg_ha": 10.0,
            "potassium_kg_ha": 100.0,
            "calcium_kg_ha": 35.0,
            "magnesium_kg_ha": 15.0,
            "engrais_recommandes": "KCl 165 kg/ha + nitrate de calcium 100 kg/ha",
            "moment_application": "Début floraison",
            "notes": "Potassium améliore la qualité et la brillance des fruits.",
        },
    ],
    "calendriers": [
        {
            "zone_agro": "niayes",
            "saison": "Saison fraîche principale",
            "mois_semis_debut": 10,
            "mois_semis_fin": 12,
            "mois_recolte_debut": 1,
            "mois_recolte_fin": 4,
            "remarques": "Meilleure qualité en saison fraîche ; moins de problèmes phytosanitaires.",
        },
        {
            "zone_agro": "niayes",
            "saison": "Saison chaude (deuxième cycle)",
            "mois_semis_debut": 3,
            "mois_semis_fin": 5,
            "mois_recolte_debut": 6,
            "mois_recolte_fin": 9,
            "remarques": "Possible mais plus de problèmes avec acariens et viroses.",
        },
        {
            "zone_agro": "casamance",
            "saison": "Toute l'année (irriguée)",
            "mois_semis_debut": 9,
            "mois_semis_fin": 1,
            "mois_recolte_debut": 12,
            "mois_recolte_fin": 4,
            "remarques": "Culture possible en saison sèche avec irrigation.",
        },
    ],
    "rendements": [
        {
            "zone_agro": None,
            "pratique": "Traditionnel",
            "rendement_min_t_ha": 8.0,
            "rendement_max_t_ha": 15.0,
            "rendement_moyen_t_ha": 11.0,
            "unite": "t/ha",
            "source": "ANCAR Sénégal",
            "annee_reference": 2022,
        },
        {
            "zone_agro": None,
            "pratique": "Intensif hybrides F1",
            "rendement_min_t_ha": 20.0,
            "rendement_max_t_ha": 40.0,
            "rendement_moyen_t_ha": 28.0,
            "unite": "t/ha",
            "source": "ISRA Horticulture",
            "annee_reference": 2023,
        },
    ],
    "maladies": [
        {
            "nom": "Flétrissement bactérien",
            "nom_scientifique": "Ralstonia solanacearum",
            "pathogene_type": "Bactérie",
            "symptomes": "Flétrissement soudain irréversible, vasculaire bruni, maladie très contagieuse.",
            "conditions_favorables": "Sols chauds et humides, blessures racinaires, monoculture.",
            "frequence": "Très fréquente",
            "gravite": "Très élevée",
            "stade_sensible": "Toute la culture",
            "pertes_estimees": "20-100%",
            "prevention": "Rotation longue, greffage sur porte-greffe résistant (Solanum torvum).",
            "traitement": "Pas de traitement curatif ; arracher et brûler.",
        },
        {
            "nom": "Phomopsis (brûlure des tiges)",
            "nom_scientifique": "Phomopsis vexans",
            "pathogene_type": "Champignon",
            "symptomes": "Taches allongées grises sur tiges, chancre et dessèchement, taches brunes sur fruits.",
            "conditions_favorables": "Humidité élevée, températures 25-30°C, blessures.",
            "frequence": "Fréquente",
            "gravite": "Modérée à élevée",
            "stade_sensible": "Croissance végétative - Fructification",
            "pertes_estimees": "15-30%",
            "prevention": "Éviter les blessures, bonne aération, éliminer les débris.",
            "traitement": "Mancozèbe 2,5 kg/ha, Chlorothalonil 2 L/ha.",
        },
        {
            "nom": "Cercosporiose",
            "nom_scientifique": "Cercospora solani / C. melongenae",
            "pathogene_type": "Champignon",
            "symptomes": "Petites taches brunes circulaires à centre gris sur feuilles, défoliation progressive.",
            "conditions_favorables": "Humidité élevée, températures modérées, mauvaise aération.",
            "frequence": "Modérément fréquente",
            "gravite": "Modérée",
            "stade_sensible": "Croissance végétative",
            "pertes_estimees": "10-20%",
            "prevention": "Rotation, espacement suffisant, éviter l'arrosage foliaire.",
            "traitement": "Mancozèbe 2 kg/ha, Chlorothalonil.",
        },
        {
            "nom": "Viroses (CMV, TSWV)",
            "nom_scientifique": "Cucumber Mosaic Virus / Tomato Spotted Wilt Virus",
            "pathogene_type": "Virus",
            "symptomes": "Mosaïque, bronzage des feuilles, nécrose, déformation des fruits.",
            "conditions_favorables": "Présence de vecteurs (pucerons, thrips), conditions sèches.",
            "frequence": "Fréquente",
            "gravite": "Élevée",
            "stade_sensible": "Toute la culture",
            "pertes_estimees": "20-50%",
            "prevention": "Contrôler les vecteurs, utiliser semences certifiées.",
            "traitement": "Pas de curatif ; lutter contre vecteurs avec Décis, Confidor.",
        },
        {
            "nom": "Verticilliose",
            "nom_scientifique": "Verticillium dahliae",
            "pathogene_type": "Champignon",
            "symptomes": "Jaunissement et flétrissement progressif des feuilles inférieures, vasculaire brun-clair.",
            "conditions_favorables": "Sols frais, monoculture de solanacées.",
            "frequence": "Modérément fréquente",
            "gravite": "Modérée",
            "stade_sensible": "Fructification",
            "pertes_estimees": "10-25%",
            "prevention": "Rotation culturale, solarisation.",
            "traitement": "Pas de traitement curatif efficace.",
        },
    ],
    "ravageurs": [
        {
            "nom": "Doryphore de l'aubergine",
            "nom_scientifique": "Epilachna similis / Henosepilachna vigintioctopunctata",
            "type_ravageur": "Insecte défoliateur (Coléoptère)",
            "description": "Coccinelle phytophage dont les adultes et larves défolient les plants d'aubergine.",
            "symptomes_degats": "Feuilles squelettisées, forte défoliation, dessèchement rapide.",
            "frequence": "Très fréquente au Sénégal",
            "gravite": "Élevée",
            "stade_sensible": "Toute la culture",
            "pertes_estimees": "20-40%",
            "prevention": "Ramassage manuel des adultes et des pontes (face inférieure des feuilles).",
            "lutte": "Décis 2,5 EC 0,5 L/ha, Lambdacyhalothrine 0,3 L/ha, Cypermethrine 0,5 L/ha.",
        },
        {
            "nom": "Acarien tétranyque",
            "nom_scientifique": "Tetranychus urticae",
            "type_ravageur": "Acarien",
            "description": "Colonie d'acariens sous les feuilles, toile fine visible en forte infestation.",
            "symptomes_degats": "Décoloration bronzée des feuilles, dessèchement en cas d'attaque forte.",
            "frequence": "Très fréquente en saison sèche",
            "gravite": "Modérée à élevée",
            "stade_sensible": "Fructification - Maturation",
            "pertes_estimees": "15-25%",
            "prevention": "Maintenir l'humidité, aspersions d'eau sur les feuilles.",
            "lutte": "Actellic 50 EC 1 L/ha, soufre mouillable 3 kg/ha.",
        },
        {
            "nom": "Puceron de l'aubergine",
            "nom_scientifique": "Aphis gossypii",
            "type_ravageur": "Insecte piqueur-suceur",
            "description": "Colonies de pucerons verts à noirs sous les feuilles et sur les apex.",
            "symptomes_degats": "Enroulement des feuilles, miellat, fumagine, vecteur de virus.",
            "frequence": "Fréquente",
            "gravite": "Modérée",
            "stade_sensible": "Végétation - Floraison",
            "pertes_estimees": "10-20%",
            "prevention": "Pièges jaunes, favoriser les coccinelles.",
            "lutte": "Confidor 0,3 L/ha, Cypermethrine 0,5 L/ha.",
        },
        {
            "nom": "Mouche blanche",
            "nom_scientifique": "Bemisia tabaci",
            "type_ravageur": "Insecte piqueur-suceur",
            "description": "Vecteur de viroses, présence constante dans les exploitations maraîchères sénégalaises.",
            "symptomes_degats": "Fumagine, jaunissement, transmission virale.",
            "frequence": "Très fréquente",
            "gravite": "Élevée (principalement vecteur viral)",
            "stade_sensible": "Toute la culture",
            "pertes_estimees": "10-30% directement, plus par viroses",
            "prevention": "Pièges jaunes engluants, filets insect-proof.",
            "lutte": "Confidor 0,5 L/ha, Actellic 50 EC.",
        },
    ],
    "recommandations": [
        {
            "zone_agro": None,
            "categorie_reco": "Lutte contre le doryphore",
            "titre": "Surveillance quotidienne et ramassage manuel",
            "contenu": (
                "Inspecter la face inférieure des feuilles chaque matin. "
                "Ramasser et écraser les adultes jaunes et les pontes orangées. "
                "En cas de forte infestation, traiter avec Décis ou Lambdacyhalothrine ; "
                "respecter le délai avant récolte (7-14 jours selon produit)."
            ),
            "priorite": 1,
            "mois_applicable": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        },
        {
            "zone_agro": None,
            "categorie_reco": "Agronomie",
            "titre": "Greffage pour la résistance au flétrissement",
            "contenu": (
                "Greffer les plants d'aubergine sur Solanum torvum (aubergine sauvage) "
                "pour une résistance durable à Ralstonia solanacearum et aux nématodes. "
                "Cette technique est encouragée par l'ISRA dans les zones à forte pression."
            ),
            "priorite": 2,
            "mois_applicable": [10, 11, 12, 1, 2, 3],
        },
    ],
}

_CHOU = {
    "nom": "Chou",
    "nom_scientifique": "Brassica oleracea var. capitata",
    "nom_local": "Su (Wolof)",
    "famille": "Brassicaceae",
    "categorie": "maraichage",
    "icone": "🥬",
    "description": (
        "Le chou pommé est une culture maraîchère importante au Sénégal, principalement cultivée dans les Niayes "
        "en saison fraîche. Il exige beaucoup d'eau et de fertilisants mais offre de bons rendements et une "
        "bonne valeur marchande."
    ),
    "parametres_climatiques": {
        "temp_min_c": 10.0,
        "temp_opt_min_c": 15.0,
        "temp_opt_max_c": 20.0,
        "temp_max_c": 30.0,
        "pluvio_min_mm": 400,
        "pluvio_opt_mm": 600,
        "pluvio_max_mm": 1000,
        "ph_min": 6.0,
        "ph_opt_min": 6.5,
        "ph_opt_max": 7.0,
        "ph_max": 7.5,
        "texture_preferee": "Limono-argileuse à limon, bien structurée et retenant l'eau",
        "ensoleillement_h": 6.0,
    },
    "varietes": [
        {
            "nom": "Tropica Cross F1",
            "origine": "Takii Seed / Japon, adapté tropiques",
            "cycle_min_jours": 65,
            "cycle_max_jours": 80,
            "precocite": "Très précoce",
            "tolerance_secheresse": False,
            "tolerance_salinite": False,
            "zones_adaptees": ["niayes", "vallee_fleuve"],
            "rendement_potentiel_t_ha": 45.0,
            "notes": "Hybride adapté aux tropiques, pommaison compacte, résistant à la montée en graines.",
        },
        {
            "nom": "Copenhagen Market",
            "origine": "Danemark, large diffusion internationale",
            "cycle_min_jours": 80,
            "cycle_max_jours": 100,
            "precocite": "Mi-saison",
            "tolerance_secheresse": False,
            "tolerance_salinite": False,
            "zones_adaptees": ["niayes"],
            "rendement_potentiel_t_ha": 30.0,
            "notes": "Variété classique à pomme ronde ferme, très populaire chez les producteurs des Niayes.",
        },
        {
            "nom": "Gloria F1",
            "origine": "Nunhems / Pays-Bas",
            "cycle_min_jours": 70,
            "cycle_max_jours": 85,
            "precocite": "Précoce",
            "tolerance_secheresse": False,
            "tolerance_salinite": False,
            "zones_adaptees": ["niayes", "vallee_fleuve"],
            "rendement_potentiel_t_ha": 50.0,
            "notes": "Hybride F1 très productif, pommes de 2-3 kg, bien adapté à la saison fraîche sénégalaise.",
        },
        {
            "nom": "Caraflex F1",
            "origine": "Bejo / Pays-Bas",
            "cycle_min_jours": 70,
            "cycle_max_jours": 90,
            "precocite": "Précoce",
            "tolerance_secheresse": False,
            "tolerance_salinite": False,
            "zones_adaptees": ["niayes"],
            "rendement_potentiel_t_ha": 35.0,
            "notes": "Chou pointu à feuilles tendres, de plus en plus populaire pour les marchés urbains.",
        },
    ],
    "stades": [
        {
            "ordre": 1,
            "nom_stade": "Pépinière",
            "jours_debut": 0,
            "jours_fin": 7,
            "description": "Semis en pépinière ombragée ; germination rapide en 5-7 jours.",
            "actions_cles": [
                "Semer en lignes sur planches surélevées bien ameublies",
                "Couvrir légèrement de terre fine",
                "Maintenir humidité et ombrage modéré",
                "Traitement préventif fongicide dès levée",
            ],
            "indicateurs_visuels": "Cotylédons réniformes caractéristiques des crucifères.",
        },
        {
            "ordre": 2,
            "nom_stade": "Croissance en pépinière",
            "jours_debut": 7,
            "jours_fin": 30,
            "description": "Développement des premières feuilles vraies ; plants prêts à repiquer en 25-30 jours.",
            "actions_cles": [
                "Arroser 2 fois par jour",
                "Désherber manuellement",
                "Traiter contre fonte des semis si nécessaire",
                "Habituer progressivement au plein soleil",
            ],
            "indicateurs_visuels": "Plants de 10-15 cm à 4-5 feuilles, tige robuste.",
        },
        {
            "ordre": 3,
            "nom_stade": "Repiquage et installation",
            "jours_debut": 30,
            "jours_fin": 45,
            "description": "Repiquage à 50x40 cm ; reprise en 7-10 jours avec arrosage régulier.",
            "actions_cles": [
                "Repiquer en soirée ou temps couvert",
                "Arroser abondamment",
                "Appliquer fumier de fond incorporé",
                "Surveiller les limaces et les insectes",
            ],
            "indicateurs_visuels": "Nouvelles feuilles brillantes et dressées.",
        },
        {
            "ordre": 4,
            "nom_stade": "Croissance végétative (rosette)",
            "jours_debut": 45,
            "jours_fin": 65,
            "description": "Développement des feuilles extérieures ; la plante forme une rosette étalée.",
            "actions_cles": [
                "Apporter fumure azotée (urée 60 kg/ha)",
                "Désherber et biner régulièrement",
                "Surveiller la teigne des crucifères et les pucerons",
                "Maintenir irrigation tous les 2 jours",
            ],
            "indicateurs_visuels": "Grande rosette de feuilles vert-bleuté, cœur de la plante en formation.",
        },
        {
            "ordre": 5,
            "nom_stade": "Pommaison",
            "jours_debut": 65,
            "jours_fin": 90,
            "description": "Les feuilles intérieures s'enroulent pour former la pomme ; stade déterminant pour le rendement.",
            "actions_cles": [
                "Maintenir irrigation régulière (critique)",
                "Apporter potassium (KCl 60 kg/ha)",
                "Surveiller l'hernie des crucifères",
                "Ne pas laisser manquer d'eau (pomme éclate sinon)",
            ],
            "indicateurs_visuels": "Pomme bien formée et compacte, feuilles extérieures bien étalées.",
        },
        {
            "ordre": 6,
            "nom_stade": "Maturation et récolte",
            "jours_debut": 90,
            "jours_fin": 110,
            "description": "La pomme est bien formée et ferme ; récolte au bon stade avant montée.",
            "actions_cles": [
                "Récolter quand la pomme est dure et bien formée",
                "Couper avec 3-4 feuilles de protection",
                "Conditionner à l'ombre pour la vente",
                "Ne pas retarder la récolte (risque d'éclatement)",
            ],
            "indicateurs_visuels": "Pomme ferme et compacte, son résistant au test de la main.",
        },
    ],
    "besoins_eau": [
        {
            "stade": "Pépinière",
            "besoin_mm_semaine": 25.0,
            "sensibilite": "Élevée",
            "frequence_irrigation": "2 fois par jour",
            "notes": "Sol toujours humide sans excès.",
        },
        {
            "stade": "Repiquage - Installation",
            "besoin_mm_semaine": 45.0,
            "sensibilite": "Très élevée",
            "frequence_irrigation": "Quotidienne",
            "notes": "Arrosage copieux indispensable à la reprise.",
        },
        {
            "stade": "Croissance végétative",
            "besoin_mm_semaine": 50.0,
            "sensibilite": "Élevée",
            "frequence_irrigation": "Tous les 2 jours",
            "notes": "Le chou est une grande consommatrice d'eau.",
        },
        {
            "stade": "Pommaison",
            "besoin_mm_semaine": 60.0,
            "sensibilite": "Très élevée",
            "frequence_irrigation": "Tous les 2 jours voire quotidienne",
            "notes": "Manque d'eau = pomme petite ; excès soudain = éclatement des pommes.",
        },
        {
            "stade": "Maturation",
            "besoin_mm_semaine": 30.0,
            "sensibilite": "Modérée",
            "frequence_irrigation": "Tous les 3 jours",
            "notes": "Réduire légèrement avant récolte pour faciliter la conservation.",
        },
    ],
    "besoins_nutritionnels": [
        {
            "stade": "Fond de plantation",
            "azote_kg_ha": 0.0,
            "phosphore_kg_ha": 80.0,
            "potassium_kg_ha": 80.0,
            "calcium_kg_ha": 40.0,
            "magnesium_kg_ha": 15.0,
            "engrais_recommandes": "Fumier 20 t/ha + TSP 175 kg/ha + chaux agricole si pH <6",
            "moment_application": "Avant repiquage",
            "notes": "Le chou est très exigeant en calcium (risque de nécrose marginale sinon).",
        },
        {
            "stade": "Croissance végétative",
            "azote_kg_ha": 100.0,
            "phosphore_kg_ha": 20.0,
            "potassium_kg_ha": 60.0,
            "calcium_kg_ha": 30.0,
            "magnesium_kg_ha": 12.0,
            "engrais_recommandes": "Urée 220 kg/ha en 3 apports fractionnés",
            "moment_application": "J+15, J+30, J+45 après repiquage",
            "notes": "Fractionnement indispensable pour éviter les pertes par lessivage.",
        },
        {
            "stade": "Pommaison",
            "azote_kg_ha": 40.0,
            "phosphore_kg_ha": 0.0,
            "potassium_kg_ha": 100.0,
            "calcium_kg_ha": 40.0,
            "magnesium_kg_ha": 15.0,
            "engrais_recommandes": "KCl 165 kg/ha + nitrate de calcium 100 kg/ha",
            "moment_application": "Début pommaison visible",
            "notes": "Calcium critique pour la qualité et la prévention de la nécrose marginale.",
        },
    ],
    "calendriers": [
        {
            "zone_agro": "niayes",
            "saison": "Saison fraîche principale",
            "mois_semis_debut": 10,
            "mois_semis_fin": 12,
            "mois_recolte_debut": 1,
            "mois_recolte_fin": 4,
            "remarques": "Zone de production principale ; températures fraîches favorables à la pommaison.",
        },
        {
            "zone_agro": "vallee_fleuve",
            "saison": "Contre-saison froide",
            "mois_semis_debut": 10,
            "mois_semis_fin": 11,
            "mois_recolte_debut": 1,
            "mois_recolte_fin": 3,
            "remarques": "Températures fraîches favorables en contre-saison dans la vallée.",
        },
    ],
    "rendements": [
        {
            "zone_agro": None,
            "pratique": "Traditionnel",
            "rendement_min_t_ha": 15.0,
            "rendement_max_t_ha": 25.0,
            "rendement_moyen_t_ha": 20.0,
            "unite": "t/ha",
            "source": "ANCAR Sénégal",
            "annee_reference": 2022,
        },
        {
            "zone_agro": None,
            "pratique": "Intensif avec hybrides F1",
            "rendement_min_t_ha": 35.0,
            "rendement_max_t_ha": 60.0,
            "rendement_moyen_t_ha": 45.0,
            "unite": "t/ha",
            "source": "ISRA Camberene",
            "annee_reference": 2023,
        },
    ],
    "maladies": [
        {
            "nom": "Hernie des crucifères",
            "nom_scientifique": "Plasmodiophora brassicae",
            "pathogene_type": "Protiste (Rhizaire)",
            "symptomes": "Galles sur racines, rabougrissement, jaunissement, flétrissement par chaleur.",
            "conditions_favorables": "Sol acide (<6,5), humide, monoculture de crucifères.",
            "frequence": "Fréquente dans les Niayes",
            "gravite": "Très élevée",
            "stade_sensible": "Toute la culture",
            "pertes_estimees": "20-80%",
            "prevention": "pH >6,5 (chaulage), rotation longue (5 ans), drainage.",
            "traitement": "Chaulage préventif (chaux vive 2 t/ha), pas de curatif efficace.",
        },
        {
            "nom": "Fonte des semis",
            "nom_scientifique": "Pythium spp. / Rhizoctonia solani",
            "pathogene_type": "Champignon / Oomycète",
            "symptomes": "Pourriture du collet en pépinière, effondrement des plants.",
            "conditions_favorables": "Sol trop humide, températures fraîches, forte densité.",
            "frequence": "Fréquente en pépinière",
            "gravite": "Élevée en pépinière",
            "stade_sensible": "Pépinière",
            "pertes_estimees": "10-40% en pépinière",
            "prevention": "Substrat sain, bon drainage, rotation des planches.",
            "traitement": "Mancozèbe en drench, sulfate de cuivre.",
        },
        {
            "nom": "Alternariose des crucifères",
            "nom_scientifique": "Alternaria brassicae / A. brassicicola",
            "pathogene_type": "Champignon",
            "symptomes": "Taches brun-noir concentriques sur feuilles et pommes, moisissures noires.",
            "conditions_favorables": "Humidité élevée, températures 18-25°C.",
            "frequence": "Fréquente",
            "gravite": "Modérée",
            "stade_sensible": "Pommaison - Récolte",
            "pertes_estimees": "10-25%",
            "prevention": "Espacement suffisant, éviter arrosage foliaire.",
            "traitement": "Mancozèbe 2,5 kg/ha, Chlorothalonil 2 L/ha.",
        },
        {
            "nom": "Mildiou des crucifères",
            "nom_scientifique": "Peronospora parasitica",
            "pathogene_type": "Oomycète",
            "symptomes": "Taches jaunes anguleuses sur feuilles, duvet blanc grisâtre en face inférieure.",
            "conditions_favorables": "Humidité élevée, températures fraîches (10-20°C), nuits froides.",
            "frequence": "Modérément fréquente",
            "gravite": "Modérée",
            "stade_sensible": "Pépinière - Croissance végétative",
            "pertes_estimees": "10-20%",
            "prevention": "Éviter excès humidité, aérer la culture.",
            "traitement": "Mancozèbe 2 kg/ha, Chlorothalonil.",
        },
    ],
    "ravageurs": [
        {
            "nom": "Teigne des crucifères",
            "nom_scientifique": "Plutella xylostella",
            "type_ravageur": "Insecte défoliateur (Lépidoptère)",
            "description": "Micro-lépidoptère dont les chenilles vert clair défolient intensément les crucifères.",
            "symptomes_degats": "Fenêtres transparentes sur feuilles, défoliation sévère, pommes endommagées.",
            "frequence": "Très fréquente, ravageur numéro 1 du chou",
            "gravite": "Très élevée",
            "stade_sensible": "Toute la culture",
            "pertes_estimees": "30-100% sans lutte",
            "prevention": "Filets insect-proof, pièges à phéromones, plantes-pièges.",
            "lutte": "Décis 2,5 EC 0,5 L/ha, Lambdacyhalothrine 0,3 L/ha, Bacillus thuringiensis (bio).",
        },
        {
            "nom": "Chenille de la pomme (Crocidolomia)",
            "nom_scientifique": "Crocidolomia pavonana",
            "type_ravageur": "Insecte défoliateur (Lépidoptère)",
            "description": "Chenilles qui pénètrent au cœur de la pomme et provoquent des dégâts irréversibles.",
            "symptomes_degats": "Galeries dans la pomme, excréments, pourriture secondaire.",
            "frequence": "Fréquente",
            "gravite": "Élevée",
            "stade_sensible": "Pommaison",
            "pertes_estimees": "20-40%",
            "prevention": "Surveiller régulièrement, retirer les feuilles atteintes.",
            "lutte": "Cypermethrine 0,5 L/ha, Décis 2,5 EC.",
        },
        {
            "nom": "Pucerons cendré du chou",
            "nom_scientifique": "Brevicoryne brassicae",
            "type_ravageur": "Insecte piqueur-suceur",
            "description": "Colonies denses de pucerons grisâtres sur les feuilles et au cœur de la pomme.",
            "symptomes_degats": "Déformation des feuilles, miellat, fumagine, affaiblissement général.",
            "frequence": "Fréquente",
            "gravite": "Modérée",
            "stade_sensible": "Croissance végétative - Pommaison",
            "pertes_estimees": "10-25%",
            "prevention": "Pièges jaunes, favoriser les ennemis naturels.",
            "lutte": "Confidor 0,5 L/ha, Cypermethrine 0,5 L/ha.",
        },
    ],
    "recommandations": [
        {
            "zone_agro": None,
            "categorie_reco": "Protection phytosanitaire",
            "titre": "Programme de lutte contre la teigne des crucifères",
            "contenu": (
                "Inspecter 2 fois par semaine la face inférieure des feuilles dès la reprise. "
                "Traiter au seuil de 5 chenilles/plante. "
                "Alterner Décis et Bacillus thuringiensis pour prévenir les résistances. "
                "La teigne résiste rapidement aux pyréthrinoïdes si non alternés."
            ),
            "priorite": 1,
            "mois_applicable": [10, 11, 12, 1, 2, 3, 4],
        },
        {
            "zone_agro": None,
            "categorie_reco": "Agronomie",
            "titre": "Chaulage pour prévenir la hernie des crucifères",
            "contenu": (
                "Corriger le pH à >6,5 avec de la chaux agricole avant plantation. "
                "Rotation de minimum 3-5 ans entre deux cultures de crucifères. "
                "Drainer les zones à risque pour réduire la survie de P. brassicae dans le sol."
            ),
            "priorite": 2,
            "mois_applicable": [9, 10, 11],
        },
    ],
}

_CONCOMBRE = {
    "nom": "Concombre",
    "nom_scientifique": "Cucumis sativus",
    "nom_local": "Konkonb (Wolof)",
    "famille": "Cucurbitaceae",
    "categorie": "maraichage",
    "icone": "🥒",
    "description": (
        "Le concombre est une culture maraîchère à cycle court cultivée dans les Niayes et la Vallée du Fleuve. "
        "Il est apprécié pour sa rapidité de production et sa valeur marchande sur les marchés urbains de Dakar."
    ),
    "parametres_climatiques": {
        "temp_min_c": 15.0,
        "temp_opt_min_c": 22.0,
        "temp_opt_max_c": 30.0,
        "temp_max_c": 38.0,
        "pluvio_min_mm": 400,
        "pluvio_opt_mm": 600,
        "pluvio_max_mm": 1000,
        "ph_min": 5.8,
        "ph_opt_min": 6.0,
        "ph_opt_max": 6.8,
        "ph_max": 7.2,
        "texture_preferee": "Sablo-limoneuse, bien drainée et riche en matière organique",
        "ensoleillement_h": 8.0,
    },
    "varietes": [
        {
            "nom": "Marketmore 76",
            "origine": "USA, large diffusion internationale",
            "cycle_min_jours": 55,
            "cycle_max_jours": 65,
            "precocite": "Précoce",
            "tolerance_secheresse": False,
            "tolerance_salinite": False,
            "zones_adaptees": ["niayes", "vallee_fleuve", "bassin_arachidier"],
            "rendement_potentiel_t_ha": 20.0,
            "notes": "Variété de référence très populaire, fruits vert foncé uniformes, résistance à plusieurs maladies.",
        },
        {
            "nom": "Poinsett 76",
            "origine": "USA",
            "cycle_min_jours": 60,
            "cycle_max_jours": 70,
            "precocite": "Précoce",
            "tolerance_secheresse": False,
            "tolerance_salinite": False,
            "zones_adaptees": ["niayes", "vallee_fleuve"],
            "rendement_potentiel_t_ha": 22.0,
            "notes": "Bonne résistance à l'oïdium et au mildiou, fruits de bonne qualité commerciale.",
        },
        {
            "nom": "Bador F1",
            "origine": "Nunhems / Pays-Bas",
            "cycle_min_jours": 50,
            "cycle_max_jours": 60,
            "precocite": "Très précoce",
            "tolerance_secheresse": False,
            "tolerance_salinite": False,
            "zones_adaptees": ["niayes", "vallee_fleuve"],
            "rendement_potentiel_t_ha": 35.0,
            "notes": "Hybride F1 parthenocarpique, production abondante, adapté à la saison fraîche.",
        },
        {
            "nom": "Local Niayes",
            "origine": "Sénégal (population locale)",
            "cycle_min_jours": 55,
            "cycle_max_jours": 70,
            "precocite": "Précoce",
            "tolerance_secheresse": True,
            "tolerance_salinite": True,
            "zones_adaptees": ["niayes", "bassin_arachidier"],
            "rendement_potentiel_t_ha": 12.0,
            "notes": "Variété locale rustique, moins productive mais mieux adaptée aux conditions difficiles.",
        },
    ],
    "stades": [
        {
            "ordre": 1,
            "nom_stade": "Germination",
            "jours_debut": 0,
            "jours_fin": 5,
            "description": "Semis direct en poquet ; germination rapide en 3-5 jours.",
            "actions_cles": [
                "Préparer des poquets 60x50 cm ou en lignes 80x40 cm",
                "Semer 2-3 graines par poquet à 2 cm de profondeur",
                "Arroser légèrement après semis",
                "Sol meuble et bien réchauffé",
            ],
            "indicateurs_visuels": "Cotylédons larges vert clair, levée uniforme.",
        },
        {
            "ordre": 2,
            "nom_stade": "Plantule",
            "jours_debut": 5,
            "jours_fin": 15,
            "description": "Démariage à 1-2 plants par poquet ; développement des 1ères feuilles vraies.",
            "actions_cles": [
                "Démarier au meilleur plant à J+10",
                "Arroser tous les 2 jours",
                "Traitement préventif fungicide",
                "Surveiller la fonte des semis",
            ],
            "indicateurs_visuels": "2-3 feuilles vraies caractéristiques, verts et luisantes.",
        },
        {
            "ordre": 3,
            "nom_stade": "Croissance végétative",
            "jours_debut": 15,
            "jours_fin": 30,
            "description": "Développement rapide des tiges rampantes ; installation des vrilles.",
            "actions_cles": [
                "Apporter NPK 15-15-15 (150 kg/ha)",
                "Mettre en place un tuteurage ou des filets si culture palissée",
                "Biner et désherber",
                "Surveiller les ravageurs",
            ],
            "indicateurs_visuels": "Tiges rampantes longues, vrilles bien développées.",
        },
        {
            "ordre": 4,
            "nom_stade": "Floraison",
            "jours_debut": 30,
            "jours_fin": 45,
            "description": "Floraison des fleurs mâles puis femelles ; pollinisation par les insectes.",
            "actions_cles": [
                "Maintenir irrigation régulière",
                "Apporter potassium",
                "Éviter les insecticides à heure de floraison",
                "Surveiller oïdium et mildiou",
            ],
            "indicateurs_visuels": "Fleurs jaunes mâles et femelles (base renflée), présence d'abeilles.",
        },
        {
            "ordre": 5,
            "nom_stade": "Fructification et récoltes",
            "jours_debut": 45,
            "jours_fin": 70,
            "description": "Récoltes très fréquentes toutes les 2-3 jours ; fruits récoltés jeunes.",
            "actions_cles": [
                "Récolter les fruits à 15-20 cm (selon variété) avant jaunissement",
                "Récolter fréquemment pour stimuler la production",
                "Apporter urée légère de couverture",
                "Surveiller oïdium et mouche blanche",
            ],
            "indicateurs_visuels": "Fruits vert foncé brillants, fermes, sans graines dures.",
        },
    ],
    "besoins_eau": [
        {
            "stade": "Germination",
            "besoin_mm_semaine": 20.0,
            "sensibilite": "Élevée",
            "frequence_irrigation": "Quotidienne légère",
            "notes": "Sol humide pour faciliter la germination.",
        },
        {
            "stade": "Croissance végétative",
            "besoin_mm_semaine": 35.0,
            "sensibilite": "Modérée",
            "frequence_irrigation": "Tous les 2-3 jours",
            "notes": "Éviter l'excès qui favorise les maladies fongiques.",
        },
        {
            "stade": "Floraison",
            "besoin_mm_semaine": 45.0,
            "sensibilite": "Très élevée",
            "frequence_irrigation": "Tous les 2 jours",
            "notes": "Stress hydrique = chute des fleurs femelles.",
        },
        {
            "stade": "Fructification",
            "besoin_mm_semaine": 50.0,
            "sensibilite": "Élevée",
            "frequence_irrigation": "Tous les 2 jours",
            "notes": "Irrégularité d'arrosage cause des fruits amers et difformes.",
        },
    ],
    "besoins_nutritionnels": [
        {
            "stade": "Fond de plantation",
            "azote_kg_ha": 0.0,
            "phosphore_kg_ha": 60.0,
            "potassium_kg_ha": 50.0,
            "calcium_kg_ha": 20.0,
            "magnesium_kg_ha": 10.0,
            "engrais_recommandes": "Fumier 12-15 t/ha + TSP 130 kg/ha",
            "moment_application": "Avant semis ou repiquage",
            "notes": "Incorporer le fumier bien décomposé.",
        },
        {
            "stade": "Croissance végétative",
            "azote_kg_ha": 60.0,
            "phosphore_kg_ha": 15.0,
            "potassium_kg_ha": 40.0,
            "calcium_kg_ha": 15.0,
            "magnesium_kg_ha": 8.0,
            "engrais_recommandes": "NPK 15-15-15 (200 kg/ha) en 2 apports",
            "moment_application": "J+15 et J+30 après semis",
            "notes": "Cycle court : fertiliser tôt pour maximiser les effets.",
        },
        {
            "stade": "Floraison - Fructification",
            "azote_kg_ha": 30.0,
            "phosphore_kg_ha": 0.0,
            "potassium_kg_ha": 60.0,
            "calcium_kg_ha": 20.0,
            "magnesium_kg_ha": 10.0,
            "engrais_recommandes": "KCl 100 kg/ha",
            "moment_application": "Début floraison",
            "notes": "Potassium pour la qualité des fruits.",
        },
    ],
    "calendriers": [
        {
            "zone_agro": "niayes",
            "saison": "Saison fraîche",
            "mois_semis_debut": 10,
            "mois_semis_fin": 1,
            "mois_recolte_debut": 12,
            "mois_recolte_fin": 3,
            "remarques": "Meilleure qualité gustative et moins de problèmes phytosanitaires.",
        },
        {
            "zone_agro": "niayes",
            "saison": "Saison chaude",
            "mois_semis_debut": 3,
            "mois_semis_fin": 5,
            "mois_recolte_debut": 5,
            "mois_recolte_fin": 7,
            "remarques": "Possible mais plus de problèmes oïdium et acariens ; cycle plus court.",
        },
        {
            "zone_agro": "vallee_fleuve",
            "saison": "Contre-saison froide",
            "mois_semis_debut": 10,
            "mois_semis_fin": 12,
            "mois_recolte_debut": 12,
            "mois_recolte_fin": 3,
            "remarques": "Bonne production sous irrigation dans la vallée.",
        },
    ],
    "rendements": [
        {
            "zone_agro": None,
            "pratique": "Traditionnel",
            "rendement_min_t_ha": 8.0,
            "rendement_max_t_ha": 15.0,
            "rendement_moyen_t_ha": 11.0,
            "unite": "t/ha",
            "source": "ANCAR Sénégal",
            "annee_reference": 2022,
        },
        {
            "zone_agro": None,
            "pratique": "Amélioré hybrides F1 + irrigation",
            "rendement_min_t_ha": 20.0,
            "rendement_max_t_ha": 40.0,
            "rendement_moyen_t_ha": 28.0,
            "unite": "t/ha",
            "source": "ISRA Horticulture",
            "annee_reference": 2023,
        },
    ],
    "maladies": [
        {
            "nom": "Oïdium des cucurbitacées",
            "nom_scientifique": "Podosphaera xanthii / Erysiphe cichoracearum",
            "pathogene_type": "Champignon",
            "symptomes": "Poudre blanche farineuse sur les deux faces des feuilles, jaunissement et dessèchement.",
            "conditions_favorables": "Temps sec et chaud, nuits fraîches, humidité atmosphérique élevée.",
            "frequence": "Très fréquente",
            "gravite": "Élevée",
            "stade_sensible": "Floraison - Fructification",
            "pertes_estimees": "20-40%",
            "prevention": "Variétés résistantes, bon espacement, irrigation au pied.",
            "traitement": "Soufre mouillable 3 kg/ha, Mancozèbe 2 kg/ha.",
        },
        {
            "nom": "Mildiou des cucurbitacées",
            "nom_scientifique": "Pseudoperonospora cubensis",
            "pathogene_type": "Oomycète",
            "symptomes": "Taches anguleuses jaunâtres limitées par les nervures, duvet gris-violet en face inférieure.",
            "conditions_favorables": "Temps chaud et humide, rosée abondante, saison des pluies.",
            "frequence": "Fréquente en saison des pluies",
            "gravite": "Élevée",
            "stade_sensible": "Croissance végétative - Fructification",
            "pertes_estimees": "20-50%",
            "prevention": "Variétés tolérantes, éviter arrosage foliaire, bon drainage.",
            "traitement": "Chlorothalonil 2 L/ha, Mancozèbe 2,5 kg/ha.",
        },
        {
            "nom": "Anthracnose des cucurbitacées",
            "nom_scientifique": "Colletotrichum orbiculare",
            "pathogene_type": "Champignon",
            "symptomes": "Taches aqueuses sur feuilles et fruits, pourriture déprimée orangée sur fruits.",
            "conditions_favorables": "Humidité élevée, températures chaudes.",
            "frequence": "Modérément fréquente",
            "gravite": "Modérée",
            "stade_sensible": "Fructification",
            "pertes_estimees": "10-25%",
            "prevention": "Rotation, éliminer les débris, variétés résistantes.",
            "traitement": "Mancozèbe 2 kg/ha, Chlorothalonil.",
        },
        {
            "nom": "Viroses (CMV, WMV)",
            "nom_scientifique": "Cucumber Mosaic Virus / Watermelon Mosaic Virus",
            "pathogene_type": "Virus",
            "symptomes": "Mosaïque, déformation des feuilles en feuille de fougère, fruits déformés et amers.",
            "conditions_favorables": "Présence de pucerons vecteurs, conditions sèches.",
            "frequence": "Fréquente",
            "gravite": "Élevée",
            "stade_sensible": "Toute la culture",
            "pertes_estimees": "15-40%",
            "prevention": "Contrôle des pucerons, élimination des plants malades.",
            "traitement": "Pas de curatif ; lutter contre vecteurs (Confidor).",
        },
    ],
    "ravageurs": [
        {
            "nom": "Mouche des cucurbitacées",
            "nom_scientifique": "Dacus cucurbitae / Bactrocera cucurbitae",
            "type_ravageur": "Insecte (Diptère)",
            "description": "Mouche dont les larves se développent dans les fruits ; ravageur très dommageable.",
            "symptomes_degats": "Piqûres de ponte sur fruits, pourriture interne, chute des fruits.",
            "frequence": "Très fréquente",
            "gravite": "Très élevée",
            "stade_sensible": "Fructification",
            "pertes_estimees": "20-60%",
            "prevention": "Pièges à phéromones (cue-lure), ramassage et destruction des fruits attaqués.",
            "lutte": "Appâts empoisonnés (protéine hydrolysée + Décis), Actellic 50 EC.",
        },
        {
            "nom": "Pucerons",
            "nom_scientifique": "Aphis gossypii",
            "type_ravageur": "Insecte piqueur-suceur",
            "description": "Colonies de pucerons verts sous les feuilles, vecteurs de viroses.",
            "symptomes_degats": "Enroulement des feuilles, miellat, fumagine, transmission CMV.",
            "frequence": "Fréquente",
            "gravite": "Élevée (vecteur viral)",
            "stade_sensible": "Végétation - Floraison",
            "pertes_estimees": "10-30% (+ viroses)",
            "prevention": "Pièges jaunes, bâches réfléchissantes.",
            "lutte": "Confidor 0,5 L/ha, savon insecticide.",
        },
        {
            "nom": "Acarien rouge",
            "nom_scientifique": "Tetranychus urticae",
            "type_ravageur": "Acarien",
            "description": "Acariens rouges sous les feuilles en saison sèche.",
            "symptomes_degats": "Décoloration bronzée, dessèchement précoce des feuilles.",
            "frequence": "Fréquente en saison sèche et chaude",
            "gravite": "Modérée",
            "stade_sensible": "Fructification",
            "pertes_estimees": "10-20%",
            "prevention": "Maintenir l'humidité, arroser les feuilles.",
            "lutte": "Actellic 50 EC 1 L/ha, soufre mouillable.",
        },
    ],
    "recommandations": [
        {
            "zone_agro": None,
            "categorie_reco": "Protection phytosanitaire",
            "titre": "Lutte contre la mouche des cucurbitacées",
            "contenu": (
                "Installer des pièges à cue-lure dès la floraison (1 piège/200 m²). "
                "Ramasser et enterrer les fruits attaqués. "
                "Utiliser des appâts empoisonnés (protéine hydrolysée 5% + Décis 0,05%). "
                "Ne pas laisser de fruits mûrs sur la plante."
            ),
            "priorite": 1,
            "mois_applicable": [4, 5, 6, 7, 8, 9, 10, 11],
        },
        {
            "zone_agro": None,
            "categorie_reco": "Récolte",
            "titre": "Récolte fréquente pour maintenir la production",
            "contenu": (
                "Récolter tous les 2-3 jours les fruits à taille commerciale. "
                "Un fruit laissé trop longtemps sur la plante freine la production des suivants. "
                "La couleur jaune indique un fruit trop mûr et amer."
            ),
            "priorite": 2,
            "mois_applicable": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        },
    ],
}

_PASTEQUE = {
    "nom": "Pastèque",
    "nom_scientifique": "Citrullus lanatus",
    "nom_local": "Dëkk bu weex (Wolof, lit. 'calebasse blanche')",
    "famille": "Cucurbitaceae",
    "categorie": "maraichage",
    "icone": "🍉",
    "description": (
        "La pastèque est cultivée principalement en saison sèche chaude au Sénégal, "
        "notamment dans les Niayes, le bassin arachidier et la Vallée du Fleuve. "
        "Elle est très appréciée pour sa résistance à la chaleur et sa valeur marchande élevée sur les marchés urbains."
    ),
    "parametres_climatiques": {
        "temp_min_c": 18.0,
        "temp_opt_min_c": 25.0,
        "temp_opt_max_c": 35.0,
        "temp_max_c": 42.0,
        "pluvio_min_mm": 300,
        "pluvio_opt_mm": 500,
        "pluvio_max_mm": 900,
        "ph_min": 5.5,
        "ph_opt_min": 6.0,
        "ph_opt_max": 7.0,
        "ph_max": 7.5,
        "texture_preferee": "Sablo-limoneuse légère, bien drainée ; tolère les sols sableux",
        "ensoleillement_h": 10.0,
    },
    "varietes": [
        {
            "nom": "Kaolack Local",
            "origine": "Sénégal (sélection paysanne, bassin arachidier)",
            "cycle_min_jours": 75,
            "cycle_max_jours": 90,
            "precocite": "Précoce",
            "tolerance_secheresse": True,
            "tolerance_salinite": False,
            "zones_adaptees": ["bassin_arachidier", "niayes", "senegal_oriental"],
            "rendement_potentiel_t_ha": 20.0,
            "notes": "Variété locale très rustique, fruits ronds moyens, chair rouge sucrée, bien adaptée aux sols sableux du bassin.",
        },
        {
            "nom": "Sugar Baby",
            "origine": "USA, large diffusion mondiale",
            "cycle_min_jours": 75,
            "cycle_max_jours": 85,
            "precocite": "Précoce",
            "tolerance_secheresse": True,
            "tolerance_salinite": False,
            "zones_adaptees": ["niayes", "bassin_arachidier", "vallee_fleuve"],
            "rendement_potentiel_t_ha": 25.0,
            "notes": "Fruits petits-moyens à chair très sucrée et rouge vif, populaire sur les marchés de Dakar.",
        },
        {
            "nom": "Crimson Sweet",
            "origine": "USA",
            "cycle_min_jours": 80,
            "cycle_max_jours": 95,
            "precocite": "Mi-saison",
            "tolerance_secheresse": True,
            "tolerance_salinite": False,
            "zones_adaptees": ["vallee_fleuve", "niayes", "bassin_arachidier"],
            "rendement_potentiel_t_ha": 30.0,
            "notes": "Gros fruits allongés à chair ferme rouge très sucrée, excellente conservation, adapté à l'export.",
        },
        {
            "nom": "Charleston Gray",
            "origine": "USA",
            "cycle_min_jours": 85,
            "cycle_max_jours": 100,
            "precocite": "Mi-saison à tardive",
            "tolerance_secheresse": True,
            "tolerance_salinite": True,
            "zones_adaptees": ["vallee_fleuve", "bassin_arachidier", "senegal_oriental"],
            "rendement_potentiel_t_ha": 35.0,
            "notes": "Très gros fruits allongés gris-verts, excellente résistance à la fusariose et à la sécheresse.",
        },
    ],
    "stades": [
        {
            "ordre": 1,
            "nom_stade": "Germination",
            "jours_debut": 0,
            "jours_fin": 7,
            "description": "Semis direct en poquet ; germination en 5-7 jours si sol chaud.",
            "actions_cles": [
                "Préparer des poquets larges et profonds (40x40x30 cm avec fumier)",
                "Semer 3 graines par poquet à 3 cm de profondeur",
                "Arroser légèrement après semis",
                "Écartement 2x1,5 m pour les grosses variétés",
            ],
            "indicateurs_visuels": "Cotylédons larges émergeant, levée vigoreuse.",
        },
        {
            "ordre": 2,
            "nom_stade": "Plantule - Installation",
            "jours_debut": 7,
            "jours_fin": 20,
            "description": "Démariage à 1-2 plants par poquet ; développement des premières feuilles.",
            "actions_cles": [
                "Démarier au meilleur plant à J+10-12",
                "Arroser tous les 2-3 jours",
                "Surveiller la fonte des semis",
                "Paillage recommandé pour conserver l'humidité et lutter contre les mauvaises herbes",
            ],
            "indicateurs_visuels": "2-3 feuilles vraies lobées caractéristiques.",
        },
        {
            "ordre": 3,
            "nom_stade": "Croissance végétative (ramification)",
            "jours_debut": 20,
            "jours_fin": 40,
            "description": "Développement rapide des tiges principales et secondaires rampantes.",
            "actions_cles": [
                "Apporter NPK 15-15-15 (150 kg/ha)",
                "Diriger les tiges pour optimiser l'espace",
                "Désherber à la main (difficile avec les longues tiges)",
                "Surveiller les ravageurs",
            ],
            "indicateurs_visuels": "Tiges longues rampantes, vrilles bien développées, feuilles lobées grandes.",
        },
        {
            "ordre": 4,
            "nom_stade": "Floraison",
            "jours_debut": 40,
            "jours_fin": 55,
            "description": "Fleurs mâles et femelles jaunes ; pollinisation entomophile indispensable.",
            "actions_cles": [
                "Ne pas traiter avec insecticides pendant la floraison (protection des abeilles)",
                "Maintenir irrigation régulière",
                "Marquer les premières fleurs femelles bien pollinisées",
                "Apporter bore foliaire pour améliorer la nouaison",
            ],
            "indicateurs_visuels": "Fleurs jaunes larges, fleurs femelles à base renflée.",
        },
        {
            "ordre": 5,
            "nom_stade": "Nouaison et grossissement",
            "jours_debut": 55,
            "jours_fin": 80,
            "description": "Développement des fruits ; maintien de 1-2 fruits par plante pour les grosses variétés.",
            "actions_cles": [
                "Apporter potassium abondant (KCl 150 kg/ha)",
                "Arroser régulièrement mais réduire avant maturité",
                "Surveiller oïdium et mouche des fruits",
                "Retourner délicatement les fruits pour éviter les brûlures de soleil",
            ],
            "indicateurs_visuels": "Fruits en grossissement, vrilles proches du fruit se dessèchent à maturité.",
        },
        {
            "ordre": 6,
            "nom_stade": "Maturation et récolte",
            "jours_debut": 80,
            "jours_fin": 100,
            "description": "Maturation progressive ; récolte à maturité optimale.",
            "actions_cles": [
                "Réduire l'irrigation 10-15 jours avant récolte (meilleure teneur en sucres)",
                "Tester la maturité : son creux au choc, vrille sèche",
                "Récolter avec le pédoncule",
                "Conditionner à l'ombre, éviter les chocs",
            ],
            "indicateurs_visuels": "Vrille proche du fruit sèche, tache ventrale passe de blanc à jaune, son creux au choc.",
        },
    ],
    "besoins_eau": [
        {
            "stade": "Germination",
            "besoin_mm_semaine": 20.0,
            "sensibilite": "Modérée",
            "frequence_irrigation": "Tous les 2 jours",
            "notes": "Sol humide sans engorgement.",
        },
        {
            "stade": "Croissance végétative",
            "besoin_mm_semaine": 40.0,
            "sensibilite": "Modérée",
            "frequence_irrigation": "Tous les 3-4 jours",
            "notes": "La pastèque est relativement tolérante au stress hydrique hors floraison.",
        },
        {
            "stade": "Floraison",
            "besoin_mm_semaine": 45.0,
            "sensibilite": "Élevée",
            "frequence_irrigation": "Tous les 2-3 jours",
            "notes": "Stress à la floraison réduit la nouaison.",
        },
        {
            "stade": "Grossissement des fruits",
            "besoin_mm_semaine": 55.0,
            "sensibilite": "Élevée",
            "frequence_irrigation": "Tous les 2-3 jours",
            "notes": "Besoins maximaux ; déficit = fruits petits et peu sucrés.",
        },
        {
            "stade": "Maturation",
            "besoin_mm_semaine": 15.0,
            "sensibilite": "Modérée (risque d'éclatement)",
            "frequence_irrigation": "Réduire progressivement, arrêter 10 j avant récolte",
            "notes": "Réduction de l'eau augmente la teneur en sucre (Brix) et prévient l'éclatement.",
        },
    ],
    "besoins_nutritionnels": [
        {
            "stade": "Fond de plantation",
            "azote_kg_ha": 0.0,
            "phosphore_kg_ha": 70.0,
            "potassium_kg_ha": 60.0,
            "calcium_kg_ha": 20.0,
            "magnesium_kg_ha": 12.0,
            "engrais_recommandes": "Fumier organique 15-20 t/ha par poquet + TSP 150 kg/ha",
            "moment_application": "Avant semis dans les poquets",
            "notes": "Concentrer le fumier dans les poquets pour un meilleur effet racinaire.",
        },
        {
            "stade": "Croissance végétative",
            "azote_kg_ha": 60.0,
            "phosphore_kg_ha": 15.0,
            "potassium_kg_ha": 50.0,
            "calcium_kg_ha": 15.0,
            "magnesium_kg_ha": 10.0,
            "engrais_recommandes": "NPK 15-15-15 (200 kg/ha) en 2 apports",
            "moment_application": "J+15 et J+30 après semis",
            "notes": "Apports azotés modérés ; excès favorise trop de végétation au détriment des fruits.",
        },
        {
            "stade": "Fructification - Maturation",
            "azote_kg_ha": 20.0,
            "phosphore_kg_ha": 0.0,
            "potassium_kg_ha": 120.0,
            "calcium_kg_ha": 25.0,
            "magnesium_kg_ha": 15.0,
            "engrais_recommandes": "KCl 200 kg/ha + sulfate de magnésium 50 kg/ha",
            "moment_application": "Début nouaison bien établie",
            "notes": "Potassium très élevé pour la qualité gustative (teneur en sucres) et la bonne coloration de la chair.",
        },
    ],
    "calendriers": [
        {
            "zone_agro": "niayes",
            "saison": "Saison sèche chaude",
            "mois_semis_debut": 2,
            "mois_semis_fin": 4,
            "mois_recolte_debut": 5,
            "mois_recolte_fin": 7,
            "remarques": "Production principale ; chaleur favorable et marchés urbains proches.",
        },
        {
            "zone_agro": "bassin_arachidier",
            "saison": "Fin saison des pluies",
            "mois_semis_debut": 7,
            "mois_semis_fin": 8,
            "mois_recolte_debut": 10,
            "mois_recolte_fin": 11,
            "remarques": "Culture pluviale possible en fin d'hivernage, moins de parasites.",
        },
        {
            "zone_agro": "vallee_fleuve",
            "saison": "Contre-saison chaude",
            "mois_semis_debut": 2,
            "mois_semis_fin": 5,
            "mois_recolte_debut": 5,
            "mois_recolte_fin": 8,
            "remarques": "Production irriguée avec de très bons rendements dans la vallée.",
        },
    ],
    "rendements": [
        {
            "zone_agro": None,
            "pratique": "Traditionnel",
            "rendement_min_t_ha": 10.0,
            "rendement_max_t_ha": 20.0,
            "rendement_moyen_t_ha": 15.0,
            "unite": "t/ha",
            "source": "ANCAR / DPA Sénégal",
            "annee_reference": 2022,
        },
        {
            "zone_agro": None,
            "pratique": "Amélioré avec variétés sélectionnées et intrants",
            "rendement_min_t_ha": 25.0,
            "rendement_max_t_ha": 50.0,
            "rendement_moyen_t_ha": 35.0,
            "unite": "t/ha",
            "source": "ISRA / Projets USAID Sénégal",
            "annee_reference": 2023,
        },
    ],
    "maladies": [
        {
            "nom": "Oïdium des cucurbitacées",
            "nom_scientifique": "Podosphaera xanthii",
            "pathogene_type": "Champignon",
            "symptomes": "Poudre blanche farineuse sur feuilles et tiges, jaunissement et dessèchement précoce.",
            "conditions_favorables": "Temps sec et chaud, humidité atmosphérique élevée, nuits fraîches.",
            "frequence": "Très fréquente en saison chaude",
            "gravite": "Élevée",
            "stade_sensible": "Fructification - Maturation",
            "pertes_estimees": "20-40%",
            "prevention": "Variétés résistantes, bon espacement, éviter l'excès d'azote.",
            "traitement": "Soufre mouillable 3-4 kg/ha, Mancozèbe 2 kg/ha.",
        },
        {
            "nom": "Mildiou des cucurbitacées",
            "nom_scientifique": "Pseudoperonospora cubensis",
            "pathogene_type": "Oomycète",
            "symptomes": "Taches anguleuses jaunes sur feuilles, sporulation grise en face inférieure.",
            "conditions_favorables": "Humidité élevée, chaleur, rosées nocturnes.",
            "frequence": "Fréquente en hivernage et contre-saison",
            "gravite": "Élevée",
            "stade_sensible": "Végétation - Fructification",
            "pertes_estimees": "20-50%",
            "prevention": "Bonne aération, éviter arrosage foliaire.",
            "traitement": "Chlorothalonil 2 L/ha, Mancozèbe 2,5 kg/ha.",
        },
        {
            "nom": "Fusariose (flétrissement fusarien)",
            "nom_scientifique": "Fusarium oxysporum f. sp. niveum",
            "pathogene_type": "Champignon",
            "symptomes": "Flétrissement unilatéral progressif, vasculaire brun à la coupe, mort des plants.",
            "conditions_favorables": "Sols sableux chauds, monoculture, pH acide.",
            "frequence": "Fréquente dans les sols des Niayes et du bassin arachidier",
            "gravite": "Très élevée",
            "stade_sensible": "Fructification",
            "pertes_estimees": "20-70%",
            "prevention": "Rotation de 3-4 ans, variétés résistantes (Charleston Gray), greffage.",
            "traitement": "Pas de traitement curatif ; arracher les plants malades.",
        },
        {
            "nom": "Anthracnose",
            "nom_scientifique": "Colletotrichum lagenarium",
            "pathogene_type": "Champignon",
            "symptomes": "Taches aqueuses sur feuilles, tiges et fruits ; pourriture déprimée des fruits à maturité.",
            "conditions_favorables": "Humidité élevée, températures chaudes (24-30°C).",
            "frequence": "Modérément fréquente",
            "gravite": "Modérée",
            "stade_sensible": "Fructification - Maturation",
            "pertes_estimees": "10-30%",
            "prevention": "Rotation culturale, éliminer les débris végétaux.",
            "traitement": "Mancozèbe 2 kg/ha, Chlorothalonil 2 L/ha.",
        },
        {
            "nom": "Gommose bactérienne",
            "nom_scientifique": "Acidovorax avenae subsp. citrulli",
            "pathogene_type": "Bactérie",
            "symptomes": "Taches huileuses sur feuilles, pourritures aqueuses sur fruits, exsudats bactériens.",
            "conditions_favorables": "Humidité et pluies fréquentes, températures chaudes.",
            "frequence": "Modérément fréquente",
            "gravite": "Élevée sur fruits",
            "stade_sensible": "Fructification",
            "pertes_estimees": "10-30%",
            "prevention": "Semences certifiées, éviter blessures, bonne aération.",
            "traitement": "Sulfate de cuivre tribasique, Chlorothalonil en préventif.",
        },
    ],
    "ravageurs": [
        {
            "nom": "Mouche des fruits",
            "nom_scientifique": "Bactrocera cucurbitae / Dacus demmerezi",
            "type_ravageur": "Insecte (Diptère)",
            "description": "Mouche dont les larves se développent dans les fruits après ponte.",
            "symptomes_degats": "Piqûres de ponte, galeries internes avec pourriture, chute des fruits.",
            "frequence": "Très fréquente",
            "gravite": "Très élevée",
            "stade_sensible": "Nouaison - Maturation",
            "pertes_estimees": "20-70%",
            "prevention": "Pièges à cue-lure, destruction des fruits tombés, filets de protection.",
            "lutte": "Appâts protéinés empoisonnés (Décis + protéine hydrolysée), Actellic 50 EC.",
        },
        {
            "nom": "Pucerons des cucurbitacées",
            "nom_scientifique": "Aphis gossypii",
            "type_ravageur": "Insecte piqueur-suceur",
            "description": "Colonies de pucerons verts-noirs sous les feuilles, vecteurs de viroses.",
            "symptomes_degats": "Enroulement et crispation des feuilles, transmission CMV et WMV.",
            "frequence": "Fréquente",
            "gravite": "Modérée à élevée (vecteur viral)",
            "stade_sensible": "Végétation - Floraison",
            "pertes_estimees": "10-25%",
            "prevention": "Pièges jaunes, bâches réfléchissantes.",
            "lutte": "Confidor 0,5 L/ha, Cypermethrine 0,5 L/ha.",
        },
        {
            "nom": "Vers gris (noctuelles)",
            "nom_scientifique": "Agrotis ipsilon / Spodoptera spp.",
            "type_ravageur": "Insecte défoliateur (Lépidoptère)",
            "description": "Chenilles nocturnes qui coupent les tiges des plantules au niveau du sol.",
            "symptomes_degats": "Plants coupés au collet, trous dans les jeunes fruits.",
            "frequence": "Fréquente en début de cycle",
            "gravite": "Modérée",
            "stade_sensible": "Germination - Plantule",
            "pertes_estimees": "5-20% en début de cycle",
            "prevention": "Travail du sol pour exposer les larves, pièges lumineux.",
            "lutte": "Lambdacyhalothrine 0,3 L/ha, Cypermethrine au sol en début de cycle.",
        },
        {
            "nom": "Nématodes à galles",
            "nom_scientifique": "Meloidogyne spp.",
            "type_ravageur": "Nématode",
            "description": "Nématodes endoparasites formant des galles sur les racines ; fréquents dans les Niayes.",
            "symptomes_degats": "Rabougrissement, galles racinaires, sensibilité accrue à la fusariose.",
            "frequence": "Fréquente dans les sols sableux",
            "gravite": "Élevée (synergie avec fusariose)",
            "stade_sensible": "Toute la culture",
            "pertes_estimees": "15-35%",
            "prevention": "Rotation avec céréales, solarisation, plantes antagonistes.",
            "lutte": "Solarisation du sol, plantes-pièges (Crotalaria spectabilis).",
        },
    ],
    "recommandations": [
        {
            "zone_agro": None,
            "categorie_reco": "Qualité",
            "titre": "Réduire l'arrosage pour augmenter la teneur en sucres",
            "contenu": (
                "À partir de 10-15 jours avant la récolte, réduire progressivement puis arrêter l'irrigation. "
                "Cette pratique augmente la teneur en sucres (Brix) et améliore la valeur marchande. "
                "Les fruits récoltés à maturation optimale se conservent mieux (7-14 jours)."
            ),
            "priorite": 1,
            "mois_applicable": [2, 3, 4, 5, 6, 7, 8, 9, 10],
        },
        {
            "zone_agro": None,
            "categorie_reco": "Protection phytosanitaire",
            "titre": "Programme de lutte contre la mouche des fruits",
            "contenu": (
                "Installer des pièges à cue-lure dès la floraison (1/200 m²). "
                "Ramasser et enterrer tous les fruits attaqués. "
                "Préparer des appâts empoisonnés : mélanger 500 ml de protéine hydrolysée + 50 ml de Décis + 5 L d'eau. "
                "Pulvériser 250 ml de ce mélange par point, tous les 7 jours."
            ),
            "priorite": 2,
            "mois_applicable": [2, 3, 4, 5, 6, 7, 8, 9],
        },
        {
            "zone_agro": None,
            "categorie_reco": "Agronomie",
            "titre": "Rotation pour prévenir la fusariose",
            "contenu": (
                "Ne pas planter la pastèque sur une parcelle ayant déjà reçu des cucurbitacées depuis moins de 3-4 ans. "
                "Alterner avec mil, sorgho, arachide. "
                "Dans les zones à forte pression fusarienne, adopter le greffage sur courge (Cucurbita moschata) résistante."
            ),
            "priorite": 3,
            "mois_applicable": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        },
    ],
}
