"""initial_schema

Revision ID: 753ff656feea
Revises: 
Create Date: 2026-06-12 13:57:25.777964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '753ff656feea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sc_analyses_id'), table_name='sc_analyses')
    op.drop_index(op.f('ix_sc_analyses_org_id'), table_name='sc_analyses')
    op.drop_index(op.f('ix_sc_analyses_parcelle_date'), table_name='sc_analyses')
    op.drop_index(op.f('ix_sc_analyses_parcelle_id'), table_name='sc_analyses')
    op.drop_index(op.f('ix_sc_analyses_statut'), table_name='sc_analyses')
    op.drop_table('sc_analyses')
    op.drop_index(op.f('ix_re_parametres_cle'), table_name='re_parametres')
    op.drop_table('re_parametres')
    op.drop_index(op.f('ix_re_decl_org_date'), table_name='re_declenchements')
    op.drop_index(op.f('ix_re_declenchements_acquitte'), table_name='re_declenchements')
    op.drop_index(op.f('ix_re_declenchements_declenche_le'), table_name='re_declenchements')
    op.drop_index(op.f('ix_re_declenchements_org_id'), table_name='re_declenchements')
    op.drop_index(op.f('ix_re_declenchements_regle_id'), table_name='re_declenchements')
    op.drop_table('re_declenchements')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_sc_previsions_rendement_id'), table_name='sc_previsions_rendement')
    op.drop_table('sc_previsions_rendement')
    op.drop_index(op.f('ix_as_date'), table_name='analyses_satellite')
    op.drop_index(op.f('ix_as_org'), table_name='analyses_satellite')
    op.drop_index(op.f('ix_as_parcelle'), table_name='analyses_satellite')
    op.drop_table('analyses_satellite')
    op.drop_index(op.f('ix_re_regles_active'), table_name='re_regles')
    op.drop_index(op.f('ix_re_regles_categorie'), table_name='re_regles')
    op.drop_index(op.f('ix_re_regles_categorie_active'), table_name='re_regles')
    op.drop_index(op.f('ix_re_regles_code'), table_name='re_regles')
    op.drop_index(op.f('ix_re_regles_gravite'), table_name='re_regles')
    op.drop_index(op.f('ix_re_regles_gravite_prio'), table_name='re_regles')
    op.drop_index(op.f('ix_re_regles_id'), table_name='re_regles')
    op.drop_table('re_regles')
    op.drop_index(op.f('ix_re_sessions_evaluation_org_id'), table_name='re_sessions_evaluation')
    op.drop_table('re_sessions_evaluation')
    op.drop_index(op.f('idx_ledger_user_date'), table_name='credit_ledger')
    op.drop_table('credit_ledger')
    op.drop_index(op.f('ix_re_regles_cultures_culture_id'), table_name='re_regles_cultures')
    op.drop_index(op.f('ix_re_regles_cultures_regle_id'), table_name='re_regles_cultures')
    op.drop_table('re_regles_cultures')
    op.drop_table('services')
    op.drop_index(op.f('ix_sc_cartes_analyse_type'), table_name='sc_cartes_precision')
    op.drop_index(op.f('ix_sc_cartes_precision_analyse_id'), table_name='sc_cartes_precision')
    op.drop_index(op.f('ix_sc_cartes_precision_id'), table_name='sc_cartes_precision')
    op.drop_index(op.f('ix_sc_cartes_precision_parcelle_id'), table_name='sc_cartes_precision')
    op.drop_table('sc_cartes_precision')
    op.drop_index(op.f('idx_req_user_date'), table_name='service_requests')
    op.drop_index(op.f('uniq_service_actif'), table_name='service_requests', postgresql_where="(statut = ANY (ARRAY['en_attente'::service_statut, 'en_cours'::service_statut]))")
    op.drop_table('service_requests')
    op.drop_index(op.f('ix_re_regles_entites_regle_id'), table_name='re_regles_entites')
    op.drop_table('re_regles_entites')
    op.drop_index(op.f('ix_sc_indices_parcelle_date'), table_name='sc_indices_satellitaires')
    op.drop_index(op.f('ix_sc_indices_satellitaires_id'), table_name='sc_indices_satellitaires')
    op.drop_index(op.f('ix_sc_indices_satellitaires_parcelle_id'), table_name='sc_indices_satellitaires')
    op.drop_table('sc_indices_satellitaires')
    op.drop_index(op.f('idx_purchases_user'), table_name='credit_purchases')
    op.drop_table('credit_purchases')
    op.drop_index(op.f('ix_sc_analyse_economique_id'), table_name='sc_analyse_economique')
    op.drop_table('sc_analyse_economique')
    op.drop_index(op.f('ix_exploitations_org'), table_name='exploitations')
    op.drop_index(op.f('ix_exploitations_user'), table_name='exploitations')
    op.drop_table('exploitations')
    op.drop_table('parcelles')
    op.alter_column('observations', 'type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'photo'::text"))
    op.alter_column('users', 'profil',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'producteur'::text"))
    op.drop_column('users', 'account_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('account_type', sa.TEXT(), server_default=sa.text("'particulier'::text"), autoincrement=False, nullable=False))
    op.alter_column('users', 'profil',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'producteur'::text"))
    op.alter_column('observations', 'type',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'photo'::text"))
    op.create_table('parcelles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nom', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('culture', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('superficie_ha', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True),
    sa.Column('superficie_m2', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('centre_lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('centre_lng', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('contour', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('precision_m', sa.NUMERIC(precision=8, scale=1), autoincrement=False, nullable=True),
    sa.Column('methode', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('parcelles_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('parcelles_pkey'))
    )
    op.create_table('exploitations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('parcelle_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('saison', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('surface_cultivee', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('production_estimee', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('unite_production', sa.VARCHAR(length=30), server_default=sa.text("'kg'::character varying"), autoincrement=False, nullable=True),
    sa.Column('couts_estimes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('revenus_estimes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('exploitations_org_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parcelle_id'], ['champ_parcelles.id'], name=op.f('exploitations_parcelle_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('exploitations_user_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('exploitations_pkey'))
    )
    op.create_index(op.f('ix_exploitations_user'), 'exploitations', ['user_id'], unique=False)
    op.create_index(op.f('ix_exploitations_org'), 'exploitations', ['org_id'], unique=False)
    op.create_table('sc_analyse_economique',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('analyse_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('superficie_ha', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('rendement_actuel_estime_t_ha', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('rendement_potentiel_t_ha', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('perte_volume_t_ha', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('prix_marche_fcfa_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('perte_potentielle_fcfa_ha', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cout_correction_estime_fcfa_ha', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('gain_potentiel_fcfa_ha', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('roi_estime', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['analyse_id'], ['sc_analyses.id'], name=op.f('sc_analyse_economique_analyse_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('sc_analyse_economique_pkey')),
    sa.UniqueConstraint('analyse_id', name=op.f('sc_analyse_economique_analyse_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_sc_analyse_economique_id'), 'sc_analyse_economique', ['id'], unique=False)
    op.create_table('credit_purchases',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('credits', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('montant_fcfa', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fournisseur', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('reference', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('statut', postgresql.ENUM('en_attente', 'paye', 'echoue', 'rembourse', name='paiement_statut'), server_default=sa.text("'en_attente'::paiement_statut"), autoincrement=False, nullable=False),
    sa.Column('ledger_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('cree_le', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('paye_le', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ledger_id'], ['credit_ledger.id'], name=op.f('credit_purchases_ledger_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('credit_purchases_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('credit_purchases_pkey')),
    sa.UniqueConstraint('reference', name=op.f('credit_purchases_reference_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_purchases_user'), 'credit_purchases', ['user_id', sa.literal_column('cree_le DESC')], unique=False)
    op.create_table('sc_indices_satellitaires',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('parcelle_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('analyse_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_image', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('date_calcul', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('satellite', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('ndvi', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ndre', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('savi', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('evi', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('msavi', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ndwi', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('couverture_nuages', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ndvi_label', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('ndre_label', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('savi_label', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('evi_label', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('msavi_label', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('ndwi_label', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('sentinelhub_request_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('bbox', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('expire_le', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['analyse_id'], ['sc_analyses.id'], name=op.f('sc_indices_satellitaires_analyse_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parcelle_id'], ['champ_parcelles.id'], name=op.f('sc_indices_satellitaires_parcelle_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('sc_indices_satellitaires_pkey'))
    )
    op.create_index(op.f('ix_sc_indices_satellitaires_parcelle_id'), 'sc_indices_satellitaires', ['parcelle_id'], unique=False)
    op.create_index(op.f('ix_sc_indices_satellitaires_id'), 'sc_indices_satellitaires', ['id'], unique=False)
    op.create_index(op.f('ix_sc_indices_parcelle_date'), 'sc_indices_satellitaires', ['parcelle_id', 'date_image'], unique=False)
    op.create_table('re_regles_entites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('regle_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('entite_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('entite_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['regle_id'], ['re_regles.id'], name=op.f('re_regles_entites_regle_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('re_regles_entites_pkey'))
    )
    op.create_index(op.f('ix_re_regles_entites_regle_id'), 're_regles_entites', ['regle_id'], unique=False)
    op.create_table('service_requests',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('farm_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('statut', postgresql.ENUM('en_attente', 'en_cours', 'termine', 'echoue', 'annule', name='service_statut'), server_default=sa.text("'en_attente'::service_statut"), autoincrement=False, nullable=False),
    sa.Column('credits_debites', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('entree', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('resultat', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('erreur', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cree_le', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('demarre_le', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('termine_le', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('service_requests_service_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('service_requests_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('service_requests_pkey'))
    )
    op.create_index(op.f('uniq_service_actif'), 'service_requests', ['user_id'], unique=True, postgresql_where="(statut = ANY (ARRAY['en_attente'::service_statut, 'en_cours'::service_statut]))")
    op.create_index(op.f('idx_req_user_date'), 'service_requests', ['user_id', sa.literal_column('cree_le DESC')], unique=False)
    op.create_table('sc_cartes_precision',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('analyse_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('parcelle_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type_carte', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('donnees', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('resolution_m', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nb_cellules', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['analyse_id'], ['sc_analyses.id'], name=op.f('sc_cartes_precision_analyse_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parcelle_id'], ['champ_parcelles.id'], name=op.f('sc_cartes_precision_parcelle_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('sc_cartes_precision_pkey'))
    )
    op.create_index(op.f('ix_sc_cartes_precision_parcelle_id'), 'sc_cartes_precision', ['parcelle_id'], unique=False)
    op.create_index(op.f('ix_sc_cartes_precision_id'), 'sc_cartes_precision', ['id'], unique=False)
    op.create_index(op.f('ix_sc_cartes_precision_analyse_id'), 'sc_cartes_precision', ['analyse_id'], unique=False)
    op.create_index(op.f('ix_sc_cartes_analyse_type'), 'sc_cartes_precision', ['analyse_id', 'type_carte'], unique=False)
    op.create_table('services',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('nom', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('cout_credits', sa.INTEGER(), server_default=sa.text('10'), autoincrement=False, nullable=False),
    sa.Column('actif', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('cree_le', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('services_pkey')),
    sa.UniqueConstraint('code', name=op.f('services_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('re_regles_cultures',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('regle_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('culture_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['culture_id'], ['agro_cultures.id'], name=op.f('re_regles_cultures_culture_id_fkey')),
    sa.ForeignKeyConstraint(['regle_id'], ['re_regles.id'], name=op.f('re_regles_cultures_regle_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('re_regles_cultures_pkey')),
    sa.UniqueConstraint('regle_id', 'culture_id', name=op.f('re_regles_cultures_regle_id_culture_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_re_regles_cultures_regle_id'), 're_regles_cultures', ['regle_id'], unique=False)
    op.create_index(op.f('ix_re_regles_cultures_culture_id'), 're_regles_cultures', ['culture_id'], unique=False)
    op.create_table('credit_ledger',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('delta', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('motif', postgresql.ENUM('achat', 'service', 'remboursement', 'bonus', 'ajustement', name='credit_motif'), autoincrement=False, nullable=False),
    sa.Column('solde_apres', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('service_request_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('cree_le', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['service_request_id'], ['service_requests.id'], name=op.f('fk_ledger_request')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('credit_ledger_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('credit_ledger_pkey'))
    )
    op.create_index(op.f('idx_ledger_user_date'), 'credit_ledger', ['user_id', sa.literal_column('cree_le DESC')], unique=False)
    op.create_table('re_sessions_evaluation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('parcelle_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('contexte', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('regles_evaluees', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('regles_declenchees', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('duree_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('re_sessions_evaluation_pkey'))
    )
    op.create_index(op.f('ix_re_sessions_evaluation_org_id'), 're_sessions_evaluation', ['org_id'], unique=False)
    op.create_table('re_regles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('categorie', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('sous_categorie', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('nom', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('zones_applicables', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('stades_applicables', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('mois_applicables', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('actions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('gravite', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('priorite', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('confiance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('plan_requis', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('version', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('re_regles_pkey'))
    )
    op.create_index(op.f('ix_re_regles_id'), 're_regles', ['id'], unique=False)
    op.create_index(op.f('ix_re_regles_gravite_prio'), 're_regles', ['gravite', 'priorite'], unique=False)
    op.create_index(op.f('ix_re_regles_gravite'), 're_regles', ['gravite'], unique=False)
    op.create_index(op.f('ix_re_regles_code'), 're_regles', ['code'], unique=True)
    op.create_index(op.f('ix_re_regles_categorie_active'), 're_regles', ['categorie', 'active'], unique=False)
    op.create_index(op.f('ix_re_regles_categorie'), 're_regles', ['categorie'], unique=False)
    op.create_index(op.f('ix_re_regles_active'), 're_regles', ['active'], unique=False)
    op.create_table('analyses_satellite',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('parcelle_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('ndvi_moyen', sa.NUMERIC(precision=5, scale=3), autoincrement=False, nullable=True),
    sa.Column('ndre', sa.NUMERIC(precision=5, scale=3), autoincrement=False, nullable=True),
    sa.Column('ndwi', sa.NUMERIC(precision=5, scale=3), autoincrement=False, nullable=True),
    sa.Column('zones', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('message_simple', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('couleur', sa.TEXT(), server_default=sa.text("'vert'::text"), autoincrement=False, nullable=True),
    sa.Column('source', sa.TEXT(), server_default=sa.text("'sentinel-2'::text"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('analyses_satellite_org_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parcelle_id'], ['champ_parcelles.id'], name=op.f('analyses_satellite_parcelle_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('analyses_satellite_pkey'))
    )
    op.create_index(op.f('ix_as_parcelle'), 'analyses_satellite', ['parcelle_id'], unique=False)
    op.create_index(op.f('ix_as_org'), 'analyses_satellite', ['org_id'], unique=False)
    op.create_index(op.f('ix_as_date'), 'analyses_satellite', ['date'], unique=False)
    op.create_table('sc_previsions_rendement',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('analyse_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('culture_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rendement_estime', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('rendement_potentiel', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ecart_performance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('facteurs_limitants', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('confiance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('methode', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['analyse_id'], ['sc_analyses.id'], name=op.f('sc_previsions_rendement_analyse_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['culture_id'], ['agro_cultures.id'], name=op.f('sc_previsions_rendement_culture_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sc_previsions_rendement_pkey')),
    sa.UniqueConstraint('analyse_id', name=op.f('sc_previsions_rendement_analyse_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_sc_previsions_rendement_id'), 'sc_previsions_rendement', ['id'], unique=False)
    op.create_table('wallets',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('solde', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('maj_le', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('solde >= 0', name=op.f('wallets_solde_check')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('wallets_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('wallets_pkey'))
    )
    op.create_table('re_declenchements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('regle_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('parcelle_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('analyse_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('contexte_entree', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('resultat', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('score_confiance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('declenche_le', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('acquitte', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('acquitte_le', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['regle_id'], ['re_regles.id'], name=op.f('re_declenchements_regle_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('re_declenchements_pkey'))
    )
    op.create_index(op.f('ix_re_declenchements_regle_id'), 're_declenchements', ['regle_id'], unique=False)
    op.create_index(op.f('ix_re_declenchements_org_id'), 're_declenchements', ['org_id'], unique=False)
    op.create_index(op.f('ix_re_declenchements_declenche_le'), 're_declenchements', ['declenche_le'], unique=False)
    op.create_index(op.f('ix_re_declenchements_acquitte'), 're_declenchements', ['acquitte'], unique=False)
    op.create_index(op.f('ix_re_decl_org_date'), 're_declenchements', ['org_id', 'declenche_le'], unique=False)
    op.create_table('re_parametres',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cle', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('valeur', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('categorie', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('modifiable_admin', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('re_parametres_pkey'))
    )
    op.create_index(op.f('ix_re_parametres_cle'), 're_parametres', ['cle'], unique=True)
    op.create_table('sc_analyses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('parcelle_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('culture_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('statut', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('analyse_le', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('duree_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('erreur_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('niveau_donnees', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('score_sante', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('score_vigueur', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('score_hydrique', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('score_fertilite', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('score_maladie', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('score_ravageur', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('etat_general', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('contexte_entree', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('resultat', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['culture_id'], ['agro_cultures.id'], name=op.f('sc_analyses_culture_id_fkey')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('sc_analyses_org_id_fkey')),
    sa.ForeignKeyConstraint(['parcelle_id'], ['champ_parcelles.id'], name=op.f('sc_analyses_parcelle_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('sc_analyses_pkey'))
    )
    op.create_index(op.f('ix_sc_analyses_statut'), 'sc_analyses', ['statut'], unique=False)
    op.create_index(op.f('ix_sc_analyses_parcelle_id'), 'sc_analyses', ['parcelle_id'], unique=False)
    op.create_index(op.f('ix_sc_analyses_parcelle_date'), 'sc_analyses', ['parcelle_id', 'analyse_le'], unique=False)
    op.create_index(op.f('ix_sc_analyses_org_id'), 'sc_analyses', ['org_id'], unique=False)
    op.create_index(op.f('ix_sc_analyses_id'), 'sc_analyses', ['id'], unique=False)
    # ### end Alembic commands ###
